CREATE TABLE "DABS    "."CONSUMER_ROUTE_HISTORY"  (
		  "ID" VARCHAR(20 OCTETS) NOT NULL ,
		  "SEQ_TRANSACTION_ID" VARCHAR(15 OCTETS) NOT NULL ,
		  "ACCOUNT_NO" VARCHAR(20 OCTETS) NOT NULL ,
		  "NEW_ACCOUNT_NO" VARCHAR(20 OCTETS) ,
		  "CATEGORY" VARCHAR(15 OCTETS) ,
		  "ROUTE" VARCHAR(30 OCTETS) ,
		  "ROUTE_ID" VARCHAR(30 OCTETS) ,
		  "BINDER_PAGE_NO" VARCHAR(20 OCTETS) ,
		  "SUBGROUP" VARCHAR(10 OCTETS) ,
		  "LOAD_TYPE" VARCHAR(5 OCTETS) ,
		  "SCENARIO" VARCHAR(20 OCTETS) ,
		  "FROM_OFFICE_ID" VARCHAR(20 OCTETS) ,
		  "FROM_READER_ID" VARCHAR(20 OCTETS) ,
		  "FROM_DTR_ID" VARCHAR(20 OCTETS) ,
		  "FROM_POLE_ID" VARCHAR(20 OCTETS) ,
		  "TO_OFFICE_ID" VARCHAR(20 OCTETS) ,
		  "T0_READER_ID" VARCHAR(20 OCTETS) ,
		  "T0_DTR_ID" VARCHAR(20 OCTETS) ,
		  "T0_POLE_ID" VARCHAR(20 OCTETS) ,
		  "SCREEN_ID" VARCHAR(10 OCTETS) NOT NULL ,
		  "CREATE_DATE" TIMESTAMP ,
		  "CREATED_BY" VARCHAR(20 OCTETS) ,
		  "UPDATED_BY" VARCHAR(20 OCTETS) ,
		  "UPDATE_DATE" TIMESTAMP ,
		  "MONTH" DECIMAL(2,0) ,
		  "YEAR" DECIMAL(4,0) ,
		  "DB_IP_ADDRESS" VARCHAR(20 OCTETS) ,
		  "CHECK_CONDITION" VARCHAR(40 OCTETS) )
		 IN "TS32"
		 ORGANIZE BY ROW  ;

GRANT SELECT ON TABLE "DABS    "."CONSUMER_ROUTE_HISTORY" TO ROLE "ROLE_READ_ONLY"  ;

GRANT SELECT ON TABLE "DABS    "."CONSUMER_ROUTE_HISTORY" TO USER "ZAFAR   "  ;

GRANT CONTROL ON TABLE "DABS    "."CONSUMER_ROUTE_HISTORY" TO USER "DB2INST1"  ;
