CREATE TABLE "CENTRAL_ALL"."CONSUMER_MISC_HIS"  (
		  "ID" VARCHAR(20 OCTETS) NOT NULL ,
		  "SCNO" VARCHAR(25 OCTETS) NOT NULL ,
		  "SUPP_RELEASE_DATE" TIMESTAMP ,
		  "PHONE" VARCHAR(30 OCTETS) ,
		  "EMAIL" VARCHAR(30 OCTETS) ,
		  "SERVICE_STATUS" VARCHAR(20 OCTETS) ,
		  "NAME" VARCHAR(500 OCTETS) ,
		  "ADDRESS_1" VARCHAR(200 OCTETS) ,
		  "ADDRESS_2" VARCHAR(350 OCTETS) ,
		  "ADDRESS_3" VARCHAR(300 OCTETS) ,
		  "ADDRESS_4" VARCHAR(300 OCTETS) ,
		  "CATEGORY" VARCHAR(15 OCTETS) ,
		  "LOAD_UNIT" VARCHAR(15 OCTETS) ,
		  "PHASE" VARCHAR(3 OCTETS) ,
		  "GRP" VARCHAR(3 OCTETS) ,
		  "OFFICE_ID" VARCHAR(20 OCTETS) ,
		  "TERMCOVER_NUM" VARCHAR(7 OCTETS) ,
		  "TERMCOVER_IMP" VARCHAR(15 OCTETS) ,
		  "FEEDER_NUM" VARCHAR(20 OCTETS) ,
		  "TRANS_SER_NUM" VARCHAR(30 OCTETS) ,
		  "TRANS_STRUC_CODE" VARCHAR(12 OCTETS) ,
		  "TRANS_LOCATION" VARCHAR(50 OCTETS) ,
		  "POL_NUM" VARCHAR(100 OCTETS) ,
		  "SUBSTATION_NUM" VARCHAR(15 OCTETS) ,
		  "ALTERNATE_ADDRESS_1" VARCHAR(25 OCTETS) ,
		  "ALTERNATE_ADDRESS_2" VARCHAR(25 OCTETS) ,
		  "ALTERNATE_ADDRESS_3" VARCHAR(25 OCTETS) ,
		  "ALTERNATE_ADDRESS_4" VARCHAR(25 OCTETS) ,
		  "BILLING_STATUS" VARCHAR(1 OCTETS) ,
		  "CONTRACTED_LOAD" DECIMAL(10,2) ,
		  "CONNECTED_LOAD" DECIMAL(10,2) ,
		  "LOAD_TYPE" VARCHAR(1 OCTETS) ,
		  "CAPACITOR_AVAIL" VARCHAR(1 OCTETS) ,
		  "BILL_MODE" VARCHAR(1 OCTETS) ,
		  "ED_FLAG" VARCHAR(1 OCTETS) ,
		  "ERO_CODE" VARCHAR(15 OCTETS) ,
		  "SPECIFIED_KV" DECIMAL(5,0) ,
		  "ACTUAL_KV" DECIMAL(5,0) ,
		  "LFLOAD" DECIMAL(15,2) ,
		  "DEMAND_EXEMPTION" VARCHAR(1 OCTETS) ,
		  "SERVICE_TYPE" CHAR(1 OCTETS) ,
		  "CREATED_BY" VARCHAR(20 OCTETS) NOT NULL ,
		  "CREATE_DATE" TIMESTAMP NOT NULL ,
		  "UPDATED_BY" VARCHAR(20 OCTETS) ,
		  "UPDATE_DATE" TIMESTAMP ,
		  "DB_IP_ADDRESS" VARCHAR(20 OCTETS) NOT NULL ,
		  "SOURCE_OFFICE_ID" VARCHAR(20 OCTETS) ,
		  "TARGET_OFFICE_ID" VARCHAR(20 OCTETS) ,
		  "RECORD_STATUS" VARCHAR(10 OCTETS) NOT NULL ,
		  "SCREEN_ID" VARCHAR(30 OCTETS) NOT NULL ,
		  "MONTH" DECFLOAT(16) NOT NULL ,
		  "MODULE_ID" VARCHAR(20 OCTETS) ,
		  "SUBMODULE_ID" VARCHAR(20 OCTETS) ,
		  "YEAR" DECFLOAT(16) NOT NULL ,
		  "FLAG1" VARCHAR(500 OCTETS) ,
		  "FLAG2" VARCHAR(25 OCTETS) ,
		  "FLAG3" VARCHAR(1 OCTETS) ,
		  "FLAG4" VARCHAR(4 OCTETS) ,
		  "FLAG5" VARCHAR(50 OCTETS) ,
		  "CHECK_CONDITION" VARCHAR(25 OCTETS) ,
		  "LEADER_ID" VARCHAR(20 OCTETS) ,
		  "SOCIAL_STATUS_ID" VARCHAR(20 OCTETS) ,
		  "EFFECT_DATE" TIMESTAMP ,
		  "LETTER_NO" VARCHAR(25 OCTETS) ,
		  "AREA_ID" VARCHAR(20 OCTETS) ,
		  "SURNAME" VARCHAR(50 OCTETS) ,
		  "LETTER_DATE" TIMESTAMP ,
		  "MTRCURRENTSTAT" VARCHAR(20 OCTETS) ,
		  "SUBGROUP" VARCHAR(5 OCTETS) ,
		  "RET_MONTH" VARCHAR(20 OCTETS) ,
		  "REMARKS" VARCHAR(200 OCTETS) ,
		  "APPROVED_BY" VARCHAR(30 OCTETS) ,
		  "ADDL_SDAMT" DECIMAL(10,2) ,
		  "PCB_NUMBER" VARCHAR(20 OCTETS) ,
		  "PCB_DATE" TIMESTAMP ,
		  "BCRC_NO" VARCHAR(10 OCTETS) ,
		  "BCRC_DATE" TIMESTAMP ,
		  "BANK_ID" VARCHAR(20 OCTETS) ,
		  "CSCNO" VARCHAR(20 OCTETS) ,
		  "NEW_POL_NUM" VARCHAR(20 OCTETS) ,
		  "NEW_STRUC_CODE" VARCHAR(20 OCTETS) ,
		  "NEW_AREA_ID" VARCHAR(20 OCTETS) ,
		  "NEW_AREACODE" VARCHAR(4 OCTETS) ,
		  "NEW_NAME" VARCHAR(500 OCTETS) ,
		  "NEW_SURNAME" VARCHAR(50 OCTETS) ,
		  "NEW_FHPNAME" VARCHAR(500 OCTETS) ,
		  "NEW_ADDRESS_1" VARCHAR(200 OCTETS) ,
		  "NEW_ADDRESS_2" VARCHAR(350 OCTETS) ,
		  "NEW_ADDRESS_3" VARCHAR(300 OCTETS) ,
		  "NEW_ADDRESS_4" VARCHAR(300 OCTETS) ,
		  "NEW_GRP" VARCHAR(3 OCTETS) ,
		  "NEW_SUBGROUP" VARCHAR(5 OCTETS) ,
		  "NEW_CSCNO" VARCHAR(6 OCTETS) ,
		  "TO_BE_APPROVEDBY" VARCHAR(1 OCTETS) ,
		  "REJECT_REASON" VARCHAR(60 OCTETS) ,
		  "OLD_COVER_SEALNO_1" VARCHAR(15 OCTETS) ,
		  "OLD_COVER_SEALNO_2" VARCHAR(15 OCTETS) ,
		  "OLD_COVER_SEALNO_3" VARCHAR(15 OCTETS) ,
		  "OLD_COVER_SEALNO_4" VARCHAR(15 OCTETS) ,
		  "OLD_TERMINAL_SEALNO_1" VARCHAR(15 OCTETS) ,
		  "OLD_TERMINAL_SEALNO_2" VARCHAR(15 OCTETS) ,
		  "NEW_COVER_SEALNO_1" VARCHAR(15 OCTETS) ,
		  "NEW_COVER_SEALNO_2" VARCHAR(15 OCTETS) ,
		  "NEW_COVER_SEALNO_3" VARCHAR(15 OCTETS) ,
		  "NEW_COVER_SEALNO_4" VARCHAR(15 OCTETS) ,
		  "NEW_TERMINAL_SEALNO_1" VARCHAR(15 OCTETS) ,
		  "NEW_TERMINAL_SEALNO_2" VARCHAR(15 OCTETS) ,
		  "NEW_METERNO" VARCHAR(20 OCTETS) ,
		  "OLD_METERNO" VARCHAR(20 OCTETS) ,
		  "APPROVALS" VARCHAR(20 OCTETS) ,
		  "OLD_ACCOUNT_NO" VARCHAR(20 OCTETS) ,
		  "NEW_ACCOUNT_NO" VARCHAR(20 OCTETS) ,
		  "OLDMETERDIGIT" VARCHAR(3 OCTETS) ,
		  "NEWMETERDIGIT" VARCHAR(2 OCTETS) ,
		  "CYCLE" VARCHAR(15 OCTETS) ,
		  "DHARI_YEAR" VARCHAR(4 OCTETS) ,
		  "RDG_YEAR" VARCHAR(4 OCTETS) ,
		  "ZONE_ID" VARCHAR(10 OCTETS) ,
		  "NEW_ZONE_ID" VARCHAR(10 OCTETS) )
		 IN "TS8"
		 ORGANIZE BY ROW  ;

CREATE INDEX "CENTRAL_ALL"."CONSUMERMISC_EFFECTDT" ON "CENTRAL_ALL"."CONSUMER_MISC_HIS"
		("EFFECT_DATE" ASC)

		COMPRESS NO
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "CENTRAL_ALL"."CONSUMERMISC_FLAG4" ON "CENTRAL_ALL"."CONSUMER_MISC_HIS"
		("FLAG4" ASC)

		COMPRESS NO
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "CENTRAL_ALL"."CONSUMERMISC_RSTATUS" ON "CENTRAL_ALL"."CONSUMER_MISC_HIS"
		("RECORD_STATUS" ASC)

		COMPRESS NO
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "CENTRAL_ALL"."CONSUMERMISC_SCNO" ON "CENTRAL_ALL"."CONSUMER_MISC_HIS"
		("SCNO" ASC)

		COMPRESS NO
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "CENTRAL_ALL"."CONSUMERMISC_SSTATUS" ON "CENTRAL_ALL"."CONSUMER_MISC_HIS"
		("SERVICE_STATUS" ASC)

		COMPRESS NO
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;
ALTER TABLE "CENTRAL_ALL"."CONSUMER_MISC_HIS"
	ADD CONSTRAINT "CONSUMERMISC_PK" PRIMARY KEY
		("ID") ;
CREATE ALIAS "DABS    "."CONSUMER_MISC_HIS" FOR TABLE "CENTRAL_ALL"."CONSUMER_MISC_HIS" ;

GRANT SELECT ON TABLE "CENTRAL_ALL"."CONSUMER_MISC_HIS" TO ROLE "ROLE_READ_ONLY"  ;

GRANT SELECT ON TABLE "CENTRAL_ALL"."CONSUMER_MISC_HIS" TO USER "ETLUSER "  ;

GRANT SELECT ON TABLE "CENTRAL_ALL"."CONSUMER_MISC_HIS" TO USER "ZAFAR   "  ;

GRANT CONTROL ON TABLE "CENTRAL_ALL"."CONSUMER_MISC_HIS" TO USER "DB2INST1"  ;
