CREATE TABLE "DABS    "."CMTCONSUMER_HISTORY"  (
		  "ID" VARCHAR(20 OCTETS) NOT NULL ,
		  "SCNO" VARCHAR(25 OCTETS) NOT NULL ,
		  "OLD_SCNO" VARCHAR(25 OCTETS) ,
		  "NAME" VARCHAR(100 OCTETS) ,
		  "FATHER_NAME" VARCHAR(100 OCTETS) ,
		  "GFATHER_NAME" VARCHAR(100 OCTETS) ,
		  "ADDRESS_1" VARCHAR(50 OCTETS) ,
		  "ADDRESS_2" VARCHAR(50 OCTETS) ,
		  "ADDRESS_3" VARCHAR(50 OCTETS) ,
		  "ADDRESS_4" VARCHAR(30 OCTETS) ,
		  "PHONE" VARCHAR(30 OCTETS) ,
		  "EMAIL" VARCHAR(30 OCTETS) ,
		  "HOUSE_OWNER_NAME" VARCHAR(100 OCTETS) ,
		  "HOUSE_OWNER_FNAME" VARCHAR(100 OCTETS) ,
		  "AREA_CODE" VARCHAR(30 OCTETS) ,
		  "ROUTE" VARCHAR(25 OCTETS) ,
		  "OFFICE_ID" VARCHAR(20 OCTETS) ,
		  "CATEGORY" VARCHAR(15 OCTETS) ,
		  "SUB_CATEGORY" VARCHAR(15 OCTETS) ,
		  "PHASE" VARCHAR(3 OCTETS) ,
		  "CONTRACTED_LOAD" DECIMAL(10,2) ,
		  "CONNECTED_LOAD" DECIMAL(10,2) ,
		  "LOAD_UNIT" VARCHAR(15 OCTETS) ,
		  "LOAD_TYPE" VARCHAR(1 OCTETS) ,
		  "NATURE_OF_PREMISES" VARCHAR(20 OCTETS) ,
		  "SUPP_RELEASE_DATE" TIMESTAMP(0) ,
		  "SERVICE_STATUS" VARCHAR(2 OCTETS) ,
		  "CONSUMER_STATUS" VARCHAR(3 OCTETS) ,
		  "CONSUMER_TYPE" VARCHAR(10 OCTETS) ,
		  "POL_NUM" VARCHAR(30 OCTETS) ,
		  "TRANS_LOCATION" VARCHAR(30 OCTETS) ,
		  "FEEDER_NUM" VARCHAR(20 OCTETS) ,
		  "SUBSTATION_NUM" VARCHAR(15 OCTETS) ,
		  "ALTERNATE_ADDRESS_1" VARCHAR(50 OCTETS) ,
		  "ALTERNATE_ADDRESS_2" VARCHAR(50 OCTETS) ,
		  "ALTERNATE_ADDRESS_3" VARCHAR(50 OCTETS) ,
		  "ALTERNATE_ADDRESS_4" VARCHAR(30 OCTETS) ,
		  "BILLING_CYCLE" DECIMAL(2,0) ,
		  "SHORT_NAME" VARCHAR(50 OCTETS) ,
		  "AGREEMENT_DATE" TIMESTAMP(0) ,
		  "LIGHTING_LOAD" DECIMAL(10,2) ,
		  "TOWNSHIP_LOAD" DECIMAL(15,2) ,
		  "TR_HIRE_CHARGES" DECIMAL(15,2) ,
		  "NO_OF_FEEDERS" DECIMAL(2,0) ,
		  "ADDL_TEMP_LOAD" VARCHAR(5 OCTETS) ,
		  "SUPPLY_VOLTAGE" DECIMAL(7,2) ,
		  "VOLTAGE_UNIT" VARCHAR(10 OCTETS) ,
		  "CONSTRUCTION_TYPE" VARCHAR(25 OCTETS) ,
		  "CREATED_BY" VARCHAR(20 OCTETS) NOT NULL ,
		  "CREATE_DATE" TIMESTAMP(0) ,
		  "UPDATED_BY" VARCHAR(20 OCTETS) ,
		  "UPDATE_DATE" TIMESTAMP(0) ,
		  "DB_IP_ADDRESS" VARCHAR(20 OCTETS) NOT NULL ,
		  "SOURCE_OFFICE_ID" VARCHAR(20 OCTETS) ,
		  "TARGET_OFFICE_ID" VARCHAR(20 OCTETS) ,
		  "SCREEN_ID" VARCHAR(30 OCTETS) NOT NULL ,
		  "RECORD_STATUS" VARCHAR(10 OCTETS) NOT NULL ,
		  "MONTH" DECIMAL(5,0) ,
		  "YEAR" DECIMAL(5,0) ,
		  "FLAG1" VARCHAR(10 OCTETS) ,
		  "FLAG2" VARCHAR(10 OCTETS) ,
		  "FLAG3" VARCHAR(10 OCTETS) ,
		  "FLAG4" VARCHAR(10 OCTETS) ,
		  "FLAG5" VARCHAR(10 OCTETS) ,
		  "MODULE_ID" VARCHAR(20 OCTETS) ,
		  "SUBMODULE_ID" VARCHAR(20 OCTETS) ,
		  "CHECK_CONDITION" VARCHAR(25 OCTETS) ,
		  "CAPACITOR_AVAIL" VARCHAR(1 OCTETS) ,
		  "METER_OWNERSHIP" VARCHAR(15 OCTETS) ,
		  "SBRNCH_CD" VARCHAR(15 OCTETS) ,
		  "CREDIT_HISTORY" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N' ,
		  "CHEQUEBOUNCE_DATE" TIMESTAMP(0) ,
		  "CHEQUEBOUNCE_REASON" VARCHAR(100 OCTETS) ,
		  "DEBT_FLAG" VARCHAR(10 OCTETS) ,
		  "DEBT_ACTION_FLAG" VARCHAR(10 OCTETS) ,
		  "ALLOWEDCHKCNT" DECIMAL(10,0) ,
		  "ACCOUNT_NO" VARCHAR(20 OCTETS) ,
		  "CONSUMER_ID" DECIMAL(20,0) ,
		  "COUNTRY_ID" VARCHAR(20 OCTETS) ,
		  "METERINGPOINT" VARCHAR(10 OCTETS) ,
		  "CONNECTIONEXPIREDATE" TIMESTAMP(0) ,
		  "APPROVEDPOWERFACTOR" DECIMAL(6,3) ,
		  "SERVICEREGION" VARCHAR(6 OCTETS) WITH DEFAULT 'Inner' ,
		  "ISCONSUMEROPTEDTOD" VARCHAR(1 OCTETS) ,
		  "NEXTBILLINGDATE" TIMESTAMP(0) ,
		  "BILLING_STATUS" VARCHAR(1 OCTETS) ,
		  "EFFECT_DATE" TIMESTAMP(0) ,
		  "GRP" VARCHAR(10 OCTETS) ,
		  "PERMANENT_ADDRESS_1" VARCHAR(50 OCTETS) ,
		  "PERMANENT_ADDRESS_2" VARCHAR(50 OCTETS) ,
		  "PERMANENT_ADDRESS_3" VARCHAR(50 OCTETS) ,
		  "PERMANENT_ADDRESS_4" VARCHAR(50 OCTETS) ,
		  "MTR_NUMBER" VARCHAR(15 OCTETS) ,
		  "MF_KWH" DECIMAL(10,2) ,
		  "TOTSDAMT" DECIMAL(10,2) ,
		  "SD_DATE" TIMESTAMP(0) ,
		  "GOVT_CODE_ID" VARCHAR(20 OCTETS) )
		 IN "TS8"
		 ORGANIZE BY ROW  ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."ACCOUNT_NO" IS 'contains the account number' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."ADDL_TEMP_LOAD" IS 'Additional Temporary Load' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."ADDRESS_1" IS 'Contains  address/House No' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."ADDRESS_2" IS 'Contains address/ Street' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."ADDRESS_3" IS 'Contains  address/ City' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."ADDRESS_4" IS 'Contains  address/District' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."AGREEMENT_DATE" IS 'Contains when the agreement took place' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."ALLOWEDCHKCNT" IS 'Number of allowed cheques to consumer' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."ALTERNATE_ADDRESS_1" IS 'Alternative address 1' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."ALTERNATE_ADDRESS_2" IS 'Alternative address 2' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."ALTERNATE_ADDRESS_3" IS 'Alternative address 3' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."ALTERNATE_ADDRESS_4" IS 'Alternative address 4' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."APPROVEDPOWERFACTOR" IS 'Used to store Approved Power factor' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."AREA_CODE" IS 'Contains area id' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."BILLING_CYCLE" IS 'Billing Cycle Monthly/Bimonthly/Tri-monthly etc..' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."BILLING_STATUS" IS 'Contains billing status like F-First Bill , L- Live Bill,  U- Disconnection Bill , S- Bill Stop' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."CAPACITOR_AVAIL" IS 'whether capacitor is available or not?' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."CATEGORY" IS 'Contains category' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."CHEQUEBOUNCE_DATE" IS 'contains when the cheque has been bounced' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."CHEQUEBOUNCE_REASON" IS 'contains the reason why the cheque has been bounced' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."CONNECTED_LOAD" IS 'Contains connected load' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."CONNECTIONEXPIREDATE" IS 'Contains connection expiry date (Applicable for temporary supply' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."CONSTRUCTION_TYPE" IS 'Type of construction' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."CONSUMER_ID" IS 'contains the consumer id' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."CONSUMER_STATUS" IS 'Contains status of the consumer' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."CONSUMER_TYPE" IS 'Contains Consumer Type' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."CONTRACTED_LOAD" IS 'Contains contracted load' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."COUNTRY_ID" IS 'country id' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."CREDIT_HISTORY" IS 'Credit History ,By default N' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."EFFECT_DATE" IS 'Contains Effect date of any such changes made to consumer attributes' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."EMAIL" IS 'Contains E-mail id' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."FATHER_NAME" IS 'Contains father name of the consumer' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."FEEDER_NUM" IS 'Feeder Number' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."GFATHER_NAME" IS 'Contains grand father name of the consumer' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."HOUSE_OWNER_FNAME" IS 'Contains house owner father name' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."HOUSE_OWNER_NAME" IS 'Contains house owner name' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."ID" IS 'Unique Id acts as primary key' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."ISCONSUMEROPTEDTOD" IS 'Represent whether TOD meter is opted or not' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."LIGHTING_LOAD" IS 'Load of the Lighting' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."LOAD_TYPE" IS 'Contains load type of the consumer' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."LOAD_UNIT" IS 'Contains load unit of the consumer' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."METERINGPOINT" IS 'Valid Values are PRIM for primary side metering, SEC for Secondary side metering' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."METER_OWNERSHIP" IS 'Contains premises of the consumer' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."NAME" IS 'Contains name of the consumer' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."NATURE_OF_PREMISES" IS 'Contains premises of the consumer' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."NEXTBILLINGDATE" IS 'Contains Next Billing Date' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."NO_OF_FEEDERS" IS 'Number of feeders' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."OFFICE_ID" IS 'Contains office id' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."OLD_SCNO" IS 'Contains old service no' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."PHASE" IS 'Contains phase' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."PHONE" IS 'Contains phone no' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."POL_NUM" IS 'Contains pole number' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."ROUTE" IS 'Contains route of the consumer' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."SCNO" IS 'Contains unique service no' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."SERVICEREGION" IS 'Valid values are INNER (with in utility), OUTER (for outside utility' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."SERVICE_STATUS" IS 'Contains service status' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."SHORT_NAME" IS 'Short NAME' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."SUBSTATION_NUM" IS 'Sub station number' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."SUB_CATEGORY" IS 'Contains Sub Category' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."SUPPLY_VOLTAGE" IS 'Voltage Supplied' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."SUPP_RELEASE_DATE" IS 'Contains connection release date' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."TOWNSHIP_LOAD" IS 'Load of the township like Colony' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."TRANS_LOCATION" IS 'Location of the Transformer' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."TR_HIRE_CHARGES" IS 'Transformer Hire charges' ;

COMMENT ON COLUMN "DABS    "."CMTCONSUMER_HISTORY"."VOLTAGE_UNIT" IS 'Voltage Unit' ;

CREATE INDEX "DABS    "."IX14_CMTCONSUMER_H" ON "DABS    "."CMTCONSUMER_HISTORY"
		("CHECK_CONDITION" ASC)

		COMPRESS NO
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;
ALTER TABLE "DABS    "."CMTCONSUMER_HISTORY"
	ADD CONSTRAINT "PK_CMTCONSUMER_HISTORY" PRIMARY KEY
		("ID") ;

GRANT SELECT ON TABLE "DABS    "."CMTCONSUMER_HISTORY" TO ROLE "ROLE_READ_ONLY"  ;

GRANT SELECT ON TABLE "DABS    "."CMTCONSUMER_HISTORY" TO USER "ETLUSER "  ;

GRANT SELECT ON TABLE "DABS    "."CMTCONSUMER_HISTORY" TO USER "ZAFAR   "  ;

GRANT CONTROL ON TABLE "DABS    "."CMTCONSUMER_HISTORY" TO USER "DB2INST1"  ;
