CREATE TABLE "DABS    "."MTRSTOCKINS"  (
		  "METERNO" BIGINT ,
		  "METERTYPE" VARCHAR(50 OCTETS) ,
		  "MTR_VOL" VARCHAR(50 OCTETS) ,
		  "METER_CAPACITY" VARCHAR(50 OCTETS) ,
		  "METER_DIGIT" INTEGER ,
		  "MAKE" VARCHAR(50 OCTETS) ,
		  "MF" INTEGER ,
		  "METER_DECIMAL" INTEGER ,
		  "METER_OWNESHIP" VARCHAR(50 OCTETS) ,
		  "INITIAL_RDG" VARCHAR(20 OCTETS) ,
		  "MtrSealLeft1" VARCHAR(20 OCTETS) ,
		  "MtrSealLeft2" VARCHAR(20 OCTETS) ,
		  "MtrSealright1" VARCHAR(20 OCTETS) ,
		  "MtrSealright2" VARCHAR(20 OCTETS) ,
		  "MTR_SEALDT" VARCHAR(20 OCTETS) ,
		  "MTR_ELEC_TYPE" VARCHAR(50 OCTETS) ,
		  "LOAD_TYPE" INTEGER )
		 IN "TS8"
		 ORGANIZE BY ROW  ;

GRANT SELECT ON TABLE "DABS    "."MTRSTOCKINS" TO ROLE "ROLE_READ_ONLY"  ;

GRANT SELECT ON TABLE "DABS    "."MTRSTOCKINS" TO USER "ZAFAR   "  ;

GRANT CONTROL ON TABLE "DABS    "."MTRSTOCKINS" TO USER "DB2INST1"  ;
