
CREATE TABLE "COMMON_USER"."CMTOFFICE_M"  (
		  "ID" VARCHAR(40 OCTETS) NOT NULL ,
		  "CODE" VARCHAR(10 OCTETS) NOT NULL ,
		  "NAME" VARCHAR(70 OCTETS) NOT NULL ,
		  "OFFICETYPE_ID" VARCHAR(20 OCTETS) NOT NULL ,
		  "PARENTOFFICE_ID" VARCHAR(20 OCTETS) NOT NULL ,
		  "EROOFFICE_ID" VARCHAR(20 OCTETS) ,
		  "RESPONSIBLEPERSON_ID" VARCHAR(20 OCTETS) NOT NULL ,
		  "DOOR_NO" VARCHAR(20 OCTETS) ,
		  "AREA" VARCHAR(30 OCTETS) ,
		  "STREET" VARCHAR(30 OCTETS) ,
		  "CITY" VARCHAR(30 OCTETS) ,
		  "PHONE1" VARCHAR(20 OCTETS) ,
		  "PHONE2" VARCHAR(20 OCTETS) ,
		  "PHONE3" VARCHAR(20 OCTETS) ,
		  "FAX" VARCHAR(20 OCTETS) ,
		  "EMAIL" VARCHAR(30 OCTETS) ,
		  "CREATE_DATE" TIMESTAMP(0) NOT NULL ,
		  "CREATED_BY" VARCHAR(20 OCTETS) NOT NULL ,
		  "UPDATED_BY" VARCHAR(20 OCTETS) ,
		  "UPDATE_DATE" TIMESTAMP(0) ,
		  "DB_IP_ADDRESS" VARCHAR(20 OCTETS) NOT NULL ,
		  "SOURCE_OFFICE_ID" VARCHAR(20 OCTETS) ,
		  "TARGET_OFFICE_ID" VARCHAR(20 OCTETS) ,
		  "RECORD_STATUS" VARCHAR(10 OCTETS) NOT NULL ,
		  "SCREEN_ID" VARCHAR(30 OCTETS) NOT NULL ,
		  "MONTH" DECFLOAT(16) NOT NULL ,
		  "YEAR" DECFLOAT(16) NOT NULL ,
		  "FLAG1" VARCHAR(5 OCTETS) ,
		  "FLAG2" VARCHAR(1 OCTETS) ,
		  "FLAG3" VARCHAR(1 OCTETS) ,
		  "FLAG4" VARCHAR(1 OCTETS) ,
		  "FLAG5" VARCHAR(1 OCTETS) ,
		  "CHECK_CONDITION" VARCHAR(50 OCTETS) NOT NULL ,
		  "CHECK_CONDITION1" VARCHAR(70 OCTETS) ,
		  "TIMING_FRHR" DECIMAL(2,0) ,
		  "TIMING_FRMI" DECIMAL(2,0) ,
		  "TIMING_TOHR" DECIMAL(2,0) ,
		  "TIMING_TOMI" DECIMAL(2,0) ,
		  "MODULE_ID" VARCHAR(20 OCTETS) ,
		  "SUBMODULE_ID" VARCHAR(20 OCTETS) ,
		  "UCODE" VARCHAR(4 OCTETS) NOT NULL ,
		  "IS_NETWORKED" VARCHAR(1 OCTETS) ,
		  "AUTHENTICATION_NUMBER" DECIMAL(22,0) ,
		  "OLD_UCODE" VARCHAR(4 OCTETS) )
		 IN "TS8"
		 ORGANIZE BY ROW  ;

ALTER TABLE "COMMON_USER"."CMTOFFICE_M" PCTFREE 0 ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."AREA" IS 'Contains Area of the office' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."AUTHENTICATION_NUMBER" IS 'Contains Authentication number' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."CITY" IS 'Contains in which city office is located' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."CODE" IS 'Contains The Office Code' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."DOOR_NO" IS 'Contains Door no of the office' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."EMAIL" IS 'Email ID' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."EROOFFICE_ID" IS 'Contains ERO office ID' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."FAX" IS 'FAX number' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."ID" IS 'Unique Id acts as primary key' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."IS_NETWORKED" IS 'Is connected to physical network or not' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."NAME" IS 'Contains name of the office' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."OFFICETYPE_ID" IS 'Contains office type ID' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."PARENTOFFICE_ID" IS 'Contains Parent ID of the office' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."PHONE1" IS 'Phone number' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."PHONE2" IS 'Phone number' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."PHONE3" IS 'Phone number' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."RESPONSIBLEPERSON_ID" IS 'Contains Responsible person id of the office' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."STREET" IS 'Contains Street of the office' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."TIMING_FRHR" IS 'Timing From Hour' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."TIMING_FRMI" IS 'Timing From Minutes' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."TIMING_TOHR" IS 'Timing To Hour' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."TIMING_TOMI" IS 'Timing To Minutes' ;

COMMENT ON COLUMN "COMMON_USER"."CMTOFFICE_M"."UCODE" IS 'Contains unique code of the office' ;

CREATE INDEX "COMMON_USER"."IDX_CMTOFFICE_M_PARENT" ON "COMMON_USER"."CMTOFFICE_M"
		("PARENTOFFICE_ID" ASC)

		COMPRESS NO
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;
ALTER TABLE "COMMON_USER"."CMTOFFICE_M"
	ADD CONSTRAINT "PK_CMTOFFICE_M" PRIMARY KEY
		("ID") ;

ALTER TABLE "COMMON_USER"."CMTOFFICE_M"
	ADD CONSTRAINT "UK_CMTOFFICE_M" UNIQUE
		("CHECK_CONDITION") ;
CREATE ALIAS "CENTRAL_ALL"."CMTOFFICE_M" FOR TABLE "COMMON_USER"."CMTOFFICE_M" ;
CREATE VIEW DABS.CMTCONSUMER_M AS
SELECT * FROM CENTRAL_ALL.CMTCONSUMER_M WHERE OFFICE_ID IN (SELECT ID FROM CENTRAL_ALL.CMTOFFICE_M WHERE PARENTOFFICE_ID='200') ;
CREATE VIEW DABS.CMTOFFICE_M  AS  SELECT CMO.ID, CMO.CODE, DECODE(CMO.NAME,'KABUL','KED',CMO.NAME)
NAME, CMO.OFFICETYPE_ID, CMO.PARENTOFFICE_ID, CMO.EROOFFICE_ID, CMO.RESPONSIBLEPERSON_ID,
CMO.DOOR_NO, CMO.AREA, CMO.STREET, CMO.CITY, CMO.PHONE1, CMO.PHONE2, CMO.PHONE3,
CMO.FAX, CMO.EMAIL, CMO.CREATE_DATE, CMO.CREATED_BY, CMO.UPDATED_BY, CMO.UPDATE_DATE,
CMO.DB_IP_ADDRESS, CMO.SOURCE_OFFICE_ID, CMO.TARGET_OFFICE_ID, CMO.RECORD_STATUS,
CMO.SCREEN_ID, CMO.MONTH, CMO.YEAR, CMO.FLAG1, CMO.FLAG2, CMO.FLAG3, CMO.FLAG4,
CMO.FLAG5, CMO.CHECK_CONDITION, CMO.CHECK_CONDITION1, CMO.TIMING_FRHR,
CMO.TIMING_FRMI, CMO.TIMING_TOHR, CMO.TIMING_TOMI, CMO.MODULE_ID, CMO.SUBMODULE_ID,
CMO.UCODE, CMO.IS_NETWORKED, CMO.AUTHENTICATION_NUMBER, CMO.OLD_UCODE FROM
COMMON_USER.CMTOFFICE_M CMO WHERE PARENTOFFICE_ID  IN ('-2','246','200') ;
CREATE VIEW CENTRAL_ALL.ZONE_OFFICE_CATEGORY_RELATION  AS  SELECT
DISTINCT ID, KED, ZONE, ZONE_ID, JUNCTION, JUNCTION_ID, CATEGORY, CATEGORY_ID,
PARENT_OFFICEID, RECORD_STATUS, CHECK_CONDITION, CREATE_DATE, UPDATE_DATE,
NAME,  COMM_ID, PARENT, PRIORITY,CYCLE_CYEAR,CYCLE,BILLMODE     FROM  (
   SELECT ID, KED, ZONE_NAME ZONE,ZONE_ID,junction_name JUNCTION,JUNCTION_ID,
category_name CATEGORY,CATEGORY_ID,PARENT_ID PARENT_OFFICEID,'ACTIVE' AS
RECORD_STATUS,NULL AS CHECK_CONDITION,NULL AS CREATE_DATE,NULL AS UPDATE_DATE,
NAME,COMM_ID, PARENT,PRIORITY,CYCLE_CYEAR,CYCLE,BILLMODE     FROM (
 SELECT DISTINCT B.ID AS ID,B.NAME AS KED,B.PARENTOFFICE_ID AS PARENT_ID,NULL
AS ZONE_ID,NULL AS ZONE_NAME,NULL AS JUNCTION_ID, NULL AS junction_name,NULL
AS CATEGORY_ID, NULL AS category_name,B.NAME as NAME,B.ID as COMM_ID,B.PARENTOFFICE_ID
AS PARENT,'A' AS PRIORITY,'--' AS CYCLE_CYEAR,'-' AS CYCLE,0  AS BILLMODE     FROM CENTRAL_ALL.CMTOFFICE_M A,CENTRAL_ALL.CMTOFFICE_M B     WHERE A.RECORD_STATUS='ACTIVE' AND B.RECORD_STATUS='ACTIVE' AND A.PARENTOFFICE_ID=B.ID AND B.ID='246'     UNION ALL     SELECT DISTINCT B.ID AS ID,B.NAME AS KED,B.PARENTOFFICE_ID AS PARENT_ID,NULL AS ZONE_ID,NULL AS ZONE_NAME,NULL AS JUNCTION_ID, NULL AS junction_name,NULL AS CATEGORY_ID, NULL AS category_name,B.NAME as NAME,B.ID as COMM_ID,B.PARENTOFFICE_ID AS PARENT,'K' AS PRIORITY,'--' AS CYCLE_CYEAR,'-' AS CYCLE,0  AS BILLMODE     FROM CENTRAL_ALL.CMTOFFICE_M A,CENTRAL_ALL.CMTOFFICE_M B     WHERE A.RECORD_STATUS='ACTIVE' AND B.RECORD_STATUS='ACTIVE' AND A.PARENTOFFICE_ID=B.ID AND B.ID<>'246'     UNION ALL     SELECT DISTINCT D.ID,E.NAME AS KED,E.ID AS PARENT_ID,D.ID AS ZONE_ID,D.NAME AS ZONE_NAME, NULL AS JUNCTION_ID,NULL AS JUNCTION_NAME,NULL AS CATEGORY_ID,NULL AS CATEGORY_NAME,D.NAME AS NAME,D.ID AS COMM_ID,E.ID AS PARENT, 'Z' AS PRIORITY,F.CYCLE_YEAR_DHARI AS CYCLE_CYEAR,F.CYCLE_CODE,F.BILLMODE AS BILLMODE     FROM CENTRAL_ALL.CMTOFFICE_M A,CENTRAL_ALL.ZONE_OFFICE_REL_M B,CENTRAL_ALL.ZONE_TARIFF_REL_CONGIF_M C,CENTRAL_ALL.ZONECYCLE_CONFIG_M D,CENTRAL_ALL.CMTOFFICE_M E,CENTRAL_ALL.ZONE_CYCLE_REL_M F     WHERE A.ID=B.OFFICE_ID AND B.ZONE_ID=C.ZONE_ID AND B.ZONE_ID=D.ID AND A.PARENTOFFICE_ID=E.ID AND A.RECORD_STATUS='ACTIVE' AND B.RECORD_STATUS='ACTIVE' AND C.RECORD_STATUS='ACTIVE' AND D.RECORD_STATUS='ACTIVE' AND E.RECORD_STATUS='ACTIVE' AND F.RECORD_STATUS='ACTIVE'  AND B.ZONE_ID=F.ZONE_ID AND TRUNC(SYSDATE) BETWEEN TRUNC(F.START_DATE) AND (F.FINAL_DATE) AND F.ACTIVITY='1000-2' AND B.ID<>'246'     UNION ALL     SELECT DISTINCT A.ID||D.ID AS ID,E.NAME AS KED,D.ID AS PARENT_ID,D.ID AS ZONE_ID,D.NAME AS ZONE_NAME, A.ID AS JUNCTION_ID,A.NAME AS JUNCTION_NAME,NULL AS CATEGORY_ID,NULL AS CATEGORY_NAME,A.NAME AS NAME,A.ID AS COMM_ID,D.ID AS PARENT, 'J' AS PRIORITY,'--' AS CYCLE_CYEAR,'-' AS CYCLE,0  AS BILLMODE     FROM CENTRAL_ALL.CMTOFFICE_M A,CENTRAL_ALL.ZONE_OFFICE_REL_M B,CENTRAL_ALL.ZONE_TARIFF_REL_CONGIF_M C,CENTRAL_ALL.ZONECYCLE_CONFIG_M D,CENTRAL_ALL.CMTOFFICE_M E     WHERE A.ID=B.OFFICE_ID AND B.ZONE_ID=C.ZONE_ID AND B.ZONE_ID=D.ID AND A.PARENTOFFICE_ID=E.ID AND A.RECORD_STATUS='ACTIVE' AND B.RECORD_STATUS='ACTIVE' AND C.RECORD_STATUS='ACTIVE' AND D.RECORD_STATUS='ACTIVE' AND E.RECORD_STATUS='ACTIVE' AND B.ID<>'246'     UNION ALL     SELECT DISTINCT A.ID||D.ID||C.CATEGORY_ID AS ID,E.NAME AS KED,A.ID||D.ID AS PARENT_ID,D.ID AS ZONE_ID,D.NAME AS ZONE_NAME, A.ID AS JUNCTION_ID,A.NAME AS JUNCTION_NAME,CATEGORY_ID AS CATEGORY_ID,(    SELECT NAME     FROM CENTRAL_ALL.NCTCATEGORY_M     WHERE ID=C.CATEGORY_ID) AS CATEGORY_NAME, (    SELECT REPLACE(NAME,'_',' ')     FROM CENTRAL_ALL.NCTCATEGORY_M     WHERE ID=C.CATEGORY_ID) AS NAME,C.CATEGORY_ID AS COMM_ID,A.ID AS PARENT, 'C' AS PRIORITY,'--' AS CYCLE_CYEAR,'-' AS CYCLE,0  AS BILLMODE     FROM CENTRAL_ALL.CMTOFFICE_M A,CENTRAL_ALL.ZONE_OFFICE_REL_M B,CENTRAL_ALL.ZONE_TARIFF_REL_CONGIF_M C,CENTRAL_ALL.ZONECYCLE_CONFIG_M D,CENTRAL_ALL.CMTOFFICE_M E     WHERE A.ID=B.OFFICE_ID AND B.ZONE_ID=C.ZONE_ID AND B.ZONE_ID=D.ID AND A.PARENTOFFICE_ID=E.ID AND A.RECORD_STATUS='ACTIVE' AND B.RECORD_STATUS='ACTIVE' AND C.RECORD_STATUS='ACTIVE' AND D.RECORD_STATUS='ACTIVE' AND E.RECORD_STATUS='ACTIVE' AND B.ID<>'246' )  ORDER BY TO_NUMBER(DECODE(PRIORITY,'A','1','K','2','Z','3','J','4','C','5')))  WITH NO ROW MOVEMENT
 ;
CREATE VIEW DABS.BILLING_SCHEDULE  AS  SELECT ROWNUM AS ID,ZONE_NAME,
ACTIVITY, OFFICE_ID, AREA_ID, DTR_ID, POLE_ID, START_DATE, END_DATE, GRACE_DAYS,
FINAL_DATE, PREALERT_DAYS, ALERT_TYPE,   CREATED_BY, CREATE_DATE, UPDATED_BY,
UPDATE_DATE, SOURCE_OFFICE_ID, TARGET_OFFICE_ID, SCREEN_ID, MODULE_ID,
SUBMODULE_ID, RECORD_STATUS, DB_IP_ADDRESS, MONTH, YEAR, FLAG1, FLAG2,
FLAG3, FLAG4, FLAG5,   METER_DAY, CHECK_CONDITION,ROUTE_CODE, ROUTE_CODE_DHARI,
ROUTE_CYCLE, ROUTE_CYCLE_DHARI, PRST_RDG_DATE, FROM_SEQUENCE         FROM
(         SELECT DISTINCT ZONE_NAME,'1000-2' ACTIVITY,OFFICE_ID, AREA_ID,
DTR_ID, POLE_ID,SYSDATE START_DATE,SYSDATE END_DATE,0 AS GRACE_DAYS,SYSDATE
FINAL_DATE, 0 AS PREALERT_DAYS,NULL ALERT_TYPE, '99' CREATED_BY,SYSDATE
CREATE_DATE,NULL UPDATED_BY,SYSDATE UPDATE_DATE,NULL SOURCE_OFFICE_ID,NULL
TARGET_OFFICE_ID, 'VIEW' SCREEN_ID,NULL MODULE_ID,NULL SUBMODULE_ID, RECORD_STATUS,'DB'
DB_IP_ADDRESS, MONTH(SYSDATE) AS MONTH,YEAR(SYSDATE) AS YEAR,'1' FLAG1,
FLAG2, FLAG3,NULL FLAG4, NULL FLAG5,NULL METER_DAY, NULL AS CHECK_CONDITION,
ROUTE_CODE, ROUTE_CODE_DHARI, '05'||ROUTE_CODE ROUTE_CYCLE,'05'||ROUTE_CODE_DHARI
ROUTE_CYCLE_DHARI,NULL PRST_RDG_DATE, NULL FROM_SEQUENCE     FROM CENTRAL_ALL.BILLING_SCHEDULE
            WHERE OFFICE_ID IN (            SELECT ID             FROM
CENTRAL_ALL.CMTOFFICE_M             WHERE PARENTOFFICE_ID='200') AND RECORD_STATUS='ACTIVE')
 WITH NO ROW MOVEMENT ;
CREATE TRIGGER COMMON_USER.TRIG_BRIN_CMTOFFICE_M
  NO CASCADE BEFORE INSERT
  ON COMMON_USER.CMTOFFICE_M
  REFERENCING
    NEW AS NEW
  FOR EACH ROW
BEGIN ATOMIC

	IF (NEW.RECORD_STATUS='ACTIVE') THEN

		SET NEW.CHECK_CONDITION = NEW.PARENTOFFICE_ID||','||NEW.UCODE;--

	ELSE

		SET NEW.CHECK_CONDITION = NEW.ID;--

	END IF;--

END ;

GRANT SELECT ON TABLE "COMMON_USER"."CMTOFFICE_M" TO ROLE "ROLE_READ_ONLY"  ;

GRANT SELECT ON TABLE "COMMON_USER"."CMTOFFICE_M" TO USER "ETLUSER "  ;

GRANT SELECT ON TABLE "COMMON_USER"."CMTOFFICE_M" TO USER "ZAFAR   "  ;

GRANT CONTROL ON TABLE "COMMON_USER"."CMTOFFICE_M" TO USER "DB2INST1"  ;
