
CREATE TABLE "COMMON_USER"."CSTREQUEST_M"  (
		  "ID" VARCHAR(40 OCTETS) NOT NULL ,
		  "TYPE_ID" VARCHAR(60 OCTETS) NOT NULL ,
		  "REQUEST_NATURE" VARCHAR(150 OCTETS) NOT NULL ,
		  "SERVICE_LEVEL" DECIMAL(3,0) NOT NULL ,
		  "FIRST_ESCALATION_ON" DECIMAL(3,0) ,
		  "SECOND_ESCALATION_ON" DECIMAL(3,0) ,
		  "FIRST_ESCALATIONTO_ID" VARCHAR(60 OCTETS) ,
		  "SECOND_ESCALATIONTO_ID" VARCHAR(60 OCTETS) ,
		  "RESPONSIBLEOFFICETYPE_ID" VARCHAR(60 OCTETS) NOT NULL ,
		  "REQUEST_RESOLVING_BASIS" DECIMAL(1,0) NOT NULL ,
		  "CREATED_BY" VARCHAR(60 OCTETS) NOT NULL ,
		  "CREATE_DATE" TIMESTAMP(0) NOT NULL ,
		  "UPDATED_BY" VARCHAR(60 OCTETS) ,
		  "UPDATE_DATE" TIMESTAMP(0) ,
		  "DB_IP_ADDRESS" VARCHAR(75 OCTETS) NOT NULL ,
		  "SOURCE_OFFICE_ID" VARCHAR(60 OCTETS) ,
		  "TARGET_OFFICE_ID" VARCHAR(60 OCTETS) ,
		  "RECORD_STATUS" VARCHAR(30 OCTETS) NOT NULL ,
		  "SCREEN_ID" VARCHAR(60 OCTETS) NOT NULL ,
		  "MONTH" DECFLOAT(16) NOT NULL ,
		  "YEAR" DECFLOAT(16) NOT NULL ,
		  "FLAG1" VARCHAR(3 OCTETS) ,
		  "FLAG2" VARCHAR(15 OCTETS) ,
		  "FLAG3" VARCHAR(3 OCTETS) ,
		  "FLAG4" VARCHAR(3 OCTETS) ,
		  "FLAG5" VARCHAR(3 OCTETS) ,
		  "CHECK_CONDITION" VARCHAR(150 OCTETS) NOT NULL ,
		  "IS_INSPECTION_REQUIRED" CHAR(3 OCTETS) ,
		  "INSPECTION_DURATION" DECIMAL(10,2) ,
		  "MODULE_ID" VARCHAR(60 OCTETS) ,
		  "SUBMODULE_ID" VARCHAR(60 OCTETS) ,
		  "OTHERCATAMOUNT" DECIMAL(12,2) ,
		  "CAT1AMOUNT" DECIMAL(12,2) ,
		  "PAYMENT_REQUIRED" VARCHAR(3 OCTETS) ,
		  "IS_APP_FEES_REQUIRED" VARCHAR(3 OCTETS) ,
		  "TYPE_OF_SERVICE" DECIMAL(1,0) ,
		  "IS_ESCALATION_REQUIRED" VARCHAR(3 OCTETS) ,
		  "IS_SCNO_REQUIRED" VARCHAR(3 OCTETS) ,
		  "EFFECTIVE_DATE" TIMESTAMP(0) NOT NULL ,
		  "DISPLAY_NATURE" VARCHAR(3 OCTETS) NOT NULL ,
		  "DURATION" DECIMAL(10,2) ,
		  "PENDING_BEYOND" VARCHAR(30 OCTETS) ,
		  "CONSUMER_CHANGE_STATUS" DECIMAL(2,0) ,
		  "FLAG6" VARCHAR(6 OCTETS) ,
		  "FLAG7" VARCHAR(6 OCTETS) ,
		  "ISDIRECT_PAYMENT" VARCHAR(6 OCTETS) ,
		  "ISESTIMATION_REQUIRED" VARCHAR(6 OCTETS) ,
		  "CODE" VARCHAR(9 OCTETS) ,
		  "MODULE_TYPE" VARCHAR(15 OCTETS) ,
		  "SEARCH_BY" VARCHAR(6 OCTETS) ,
		  "CONDITION" VARCHAR(60 OCTETS) ,
		  "IS_AUTO_DISPATCH" VARCHAR(15 OCTETS) ,
		  "IS_AUTO_DISPATCH_ID" VARCHAR(15 OCTETS) )
		 IN "TS8"
		 ORGANIZE BY ROW  ;
ALTER TABLE "COMMON_USER"."CSTREQUEST_M"
	ADD CONSTRAINT "CSTREQUEST_M_PK" PRIMARY KEY
		("ID") ;

ALTER TABLE "COMMON_USER"."CSTREQUEST_M"
	ADD CONSTRAINT "UK_CSTREQUEST_M" UNIQUE
		("CHECK_CONDITION") ;
CREATE ALIAS "CENTRAL_ALL"."CSTREQUEST_M" FOR TABLE "COMMON_USER"."CSTREQUEST_M" ;
CREATE ALIAS "DABS    "."CSTREQUEST_M" FOR TABLE "COMMON_USER"."CSTREQUEST_M" ;
CREATE ALIAS "DABS    "."INSTALMENT_CONFIG_M" FOR TABLE "DABS    "."CSTREQUEST_M" ;
CREATE TRIGGER "COMMON_USER"."TRIG_BRIN_CSTREQUEST_M"
  NO CASCADE BEFORE INSERT
  ON "COMMON_USER"."CSTREQUEST_M"
  REFERENCING
              NEW AS "NEW"
  FOR EACH ROW
BEGIN ATOMIC

	IF (NEW.RECORD_STATUS='ACTIVE') THEN

		SET NEW.CHECK_CONDITION = NEW.REQUEST_NATURE;--

	ELSE

		SET NEW.CHECK_CONDITION = NEW.ID;--

	END IF;--

END ;
CREATE TRIGGER "COMMON_USER"."TRIG_BRUP_CSTREQUEST_M"
  NO CASCADE BEFORE UPDATE
  ON "COMMON_USER"."CSTREQUEST_M"
  REFERENCING
              OLD AS "OLD"
              NEW AS "NEW"
  FOR EACH ROW
BEGIN ATOMIC

	DECLARE CNT INTEGER;--

	IF (NEW.RECORD_STATUS='ACTIVE') THEN

		SET NEW.CHECK_CONDITION = NEW.REQUEST_NATURE;--

	ELSE

		SET NEW.CHECK_CONDITION = NEW.ID;--

	END IF;--

END ;

GRANT SELECT ON TABLE "COMMON_USER"."CSTREQUEST_M" TO ROLE "ROLE_READ_ONLY"  ;

GRANT SELECT ON TABLE "COMMON_USER"."CSTREQUEST_M" TO USER "ETLUSER "  ;

GRANT SELECT ON TABLE "COMMON_USER"."CSTREQUEST_M" TO USER "ZAFAR   "  ;

GRANT CONTROL ON TABLE "COMMON_USER"."CSTREQUEST_M" TO USER "DB2INST1"  ;
