
CREATE TABLE "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"  (
		  "ID" VARCHAR(40 OCTETS) NOT NULL , 
		  "CONSUMER_ID" VARCHAR(20 OCTETS) , 
		  "GROUP_ID" VARCHAR(20 OCTETS) , 
		  "OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "CATEGORY_ID" VARCHAR(20 OCTETS) , 
		  "CREATED_BY" VARCHAR(10 OCTETS) NOT NULL , 
		  "CREATE_DATE" TIMESTAMP NOT NULL , 
		  "UPDATED_BY" VARCHAR(20 OCTETS) , 
		  "UPDATE_DATE" TIMESTAMP , 
		  "DB_IP_ADDRESS" VARCHAR(25 OCTETS) NOT NULL , 
		  "RECORD_STATUS" VARCHAR(10 OCTETS) NOT NULL , 
		  "SCREEN_ID" VARCHAR(30 OCTETS) , 
		  "MONTH" DECIMAL(2,0) NOT NULL , 
		  "YEAR" DECIMAL(4,0) NOT NULL , 
		  "FLAG1" VARCHAR(3 OCTETS) , 
		  "FLAG2" VARCHAR(3 OCTETS) , 
		  "FLAG3" VARCHAR(3 OCTETS) , 
		  "FLAG4" VARCHAR(3 OCTETS) , 
		  "FLAG5" VARCHAR(3 OCTETS) , 
		  "CHECK_CONDITION" VARCHAR(50 OCTETS) , 
		  "ADVANCE_AMT" DECIMAL(15,2) , 
		  "BALANCE_AMT" DECIMAL(15,2) , 
		  "DGM_STATUS" VARCHAR(10 OCTETS) , 
		  "DGM_APPROVED_DATE" TIMESTAMP , 
		  "CA_STATUS" VARCHAR(10 OCTETS) , 
		  "CA_APPROVED_DATE" TIMESTAMP , 
		  "BD_STATUS" VARCHAR(10 OCTETS) , 
		  "BD_APPROVED_DATE" TIMESTAMP , 
		  "BANK_NAME_ID" VARCHAR(10 OCTETS) , 
		  "COUNTER_USER" VARCHAR(5 OCTETS) , 
		  "COUNTER_ID" VARCHAR(15 OCTETS) , 
		  "COLLECTION_DATE" TIMESTAMP , 
		  "RECEIPT" VARCHAR(30 OCTETS) , 
		  "PAYMENT_STATUS" VARCHAR(2 OCTETS) , 
		  "PAY_APPROVED_USER" VARCHAR(5 OCTETS) , 
		  "PAY_APPROVED_DATE" TIMESTAMP , 
		  "CYCLE" VARCHAR(15 OCTETS) , 
		  "CYCLE_YEAR" VARCHAR(5 OCTETS) , 
		  "DHARI_YEAR" VARCHAR(4 OCTETS) , 
		  "REPOSITORY_ID" VARCHAR(50 OCTETS) , 
		  "ESIGN_ID" VARCHAR(50 OCTETS) , 
		  "REFERENCE_NO" VARCHAR(25 OCTETS) )   
		 IN "TBS_IX"  
		 ORGANIZE BY ROW  ;

ALTER TABLE "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER" PCTFREE 0 ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."ADVANCE_AMT" IS 'Advance Amount' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."BALANCE_AMT" IS 'Balance Amount' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."BANK_NAME_ID" IS 'Bank Name ID' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."CATEGORY_ID" IS 'Consumer Category ID' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."CHECK_CONDITION" IS 'To Check The Uniqueness' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."COLLECTION_DATE" IS 'Collection Date' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."CONSUMER_ID" IS 'Consumer ID' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."COUNTER_USER" IS 'Counter User' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."CREATED_BY" IS 'Record Created By' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."CREATE_DATE" IS 'Record Create Data' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."CYCLE" IS 'Cycle' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."CYCLE_YEAR" IS 'Cycle Year' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."DB_IP_ADDRESS" IS 'From Which IP the Record is Inserted' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."DHARI_YEAR" IS 'Dhari Year' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."ESIGN_ID" IS 'Esign ID' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."FLAG1" IS 'Migration Changes for Tracking' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."FLAG2" IS 'Migration Changes for Tracking' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."FLAG3" IS 'Migration Changes for Tracking' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."FLAG4" IS 'Migration Changes for Tracking' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."FLAG5" IS 'Migration Changes for Tracking' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."GROUP_ID" IS 'Consumer Group ID' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."ID" IS 'Unique number generated used as Primary key' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."MONTH" IS 'Month' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."OFFICE_ID" IS 'Consumer Office ID' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."PAYMENT_STATUS" IS 'Payment Status' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."PAY_APPROVED_DATE" IS 'Payment Approved Date' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."PAY_APPROVED_USER" IS 'Payment Approved User' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."RECEIPT" IS 'Receipt' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."RECORD_STATUS" IS 'Status of the Record(Active/Inactive)' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."REPOSITORY_ID" IS 'Repository ID' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."SCREEN_ID" IS 'Name of the Screen' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."UPDATED_BY" IS 'Record Updated By' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."UPDATE_DATE" IS 'Record Updated Date' ;

COMMENT ON COLUMN "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER"."YEAR" IS 'Year' ;

GRANT SELECT ON TABLE "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER" TO ROLE "ROLE_READ_ONLY"  ;

GRANT SELECT ON TABLE "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER" TO USER "ETLUSER "  ;

GRANT SELECT ON TABLE "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER" TO USER "ZAFAR   "  ;

GRANT CONTROL ON TABLE "CENTRAL_ALL"."ADVANCE_PAYMENT_MASTER" TO USER "DB2INST1"  ;
