
CREATE TABLE "CENTRAL_ALL"."ADVANCE_PAYMENT_DETAILS"  (
		  "ID" VARCHAR(20 OCTETS) , 
		  "CONSUMER_ID" VARCHAR(20 OCTETS) , 
		  "GROUP_ID" VARCHAR(20 OCTETS) , 
		  "ADVANCE_AMOUNT" DECIMAL(15,2) , 
		  "BILL_NO" VARCHAR(20 OCTETS) , 
		  "BILL_AMOUNT" DECIMAL(15,2) , 
		  "PAYMENT_DATE" TIMESTAMP , 
		  "BALANCE" DECIMAL(15,2) , 
		  "CYCLE" VARCHAR(2 OCTETS) , 
		  "CYCLE_YEAR" VARCHAR(4 OCTETS) , 
		  "DHARI_YEAR" VARCHAR(4 OCTETS) , 
		  "CREATED_BY" VARCHAR(10 OCTETS) , 
		  "CREATE_DATE" TIMESTAMP , 
		  "UPDATED_BY" VARCHAR(20 OCTETS) , 
		  "UPDATE_DATE" TIMESTAMP , 
		  "DB_IP_ADDRESS" VARCHAR(25 OCTETS) , 
		  "SOURCE_OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "TARGET_OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "RECORD_STATUS" VARCHAR(10 OCTETS) , 
		  "SCREEN_ID" VARCHAR(20 OCTETS) , 
		  "MONTH" DECFLOAT(16) , 
		  "YEAR" DECFLOAT(16) , 
		  "FLAG1" VARCHAR(5 OCTETS) , 
		  "FLAG2" VARCHAR(5 OCTETS) , 
		  "FLAG3" VARCHAR(5 OCTETS) , 
		  "FLAG4" VARCHAR(5 OCTETS) , 
		  "FLAG5" VARCHAR(5 OCTETS) , 
		  "CHECK_CONDITION" VARCHAR(100 OCTETS) , 
		  "MODULE_ID" VARCHAR(20 OCTETS) , 
		  "SUBMODULE_ID" VARCHAR(20 OCTETS) )   
		 IN "TS8"  
		 ORGANIZE BY ROW  ;

GRANT SELECT ON TABLE "CENTRAL_ALL"."ADVANCE_PAYMENT_DETAILS" TO ROLE "ROLE_READ_ONLY"  ;

GRANT SELECT ON TABLE "CENTRAL_ALL"."ADVANCE_PAYMENT_DETAILS" TO USER "ETLUSER "  ;

GRANT SELECT ON TABLE "CENTRAL_ALL"."ADVANCE_PAYMENT_DETAILS" TO USER "ZAFAR   "  ;

GRANT CONTROL ON TABLE "CENTRAL_ALL"."ADVANCE_PAYMENT_DETAILS" TO USER "DB2INST1"  ;
