
CREATE TABLE "CENTRAL_ALL"."INSTALMENT_CONFIG_M"  (
		  "ID" VARCHAR(40 OCTETS) NOT NULL , 
		  "PROVIENCE" VARCHAR(5 OCTETS) , 
		  "DESIG_ID" VARCHAR(15 OCTETS) NOT NULL , 
		  "CATEGORY_ID" VARCHAR(15 OCTETS) , 
		  "CYCLE_YEAR" VARCHAR(10 OCTETS) , 
		  "INSTALMENT_COUNT" VARCHAR(20 OCTETS) , 
		  "INSTALMENT_AMOUNT" VARCHAR(20 OCTETS) , 
		  "EFFECTIVE_DATE" TIMESTAMP , 
		  "CREATED_BY" VARCHAR(15 OCTETS) , 
		  "CREATE_DATE" TIMESTAMP , 
		  "UPDATED_BY" VARCHAR(15 OCTETS) , 
		  "UPDATE_DATE" TIMESTAMP , 
		  "DB_IP_ADDRESS" VARCHAR(20 OCTETS) , 
		  "SOURCE_OFFICE_ID" VARCHAR(15 OCTETS) , 
		  "TARGET_OFFICE_ID" VARCHAR(15 OCTETS) , 
		  "RECORD_STATUS" VARCHAR(10 OCTETS) , 
		  "SCREEN_ID" VARCHAR(30 OCTETS) , 
		  "MONTH" DECIMAL(2,0) , 
		  "YEAR" DECIMAL(4,0) , 
		  "FLAG1" VARCHAR(6 OCTETS) , 
		  "FLAG2" VARCHAR(1 OCTETS) , 
		  "CHECK_CONDITION" VARCHAR(50 OCTETS) , 
		  "GRACE_DAYS" VARCHAR(1 OCTETS) )   
		 IN "TBS_NEW_T"  
		 ORGANIZE BY ROW  ;

ALTER TABLE "CENTRAL_ALL"."INSTALMENT_CONFIG_M" PCTFREE 0 ;

CREATE INDEX "CENTRAL_ALL"."IX_INSTALMENT_CONFIG_M_CATID" ON "CENTRAL_ALL"."INSTALMENT_CONFIG_M" 
		("CATEGORY_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "CENTRAL_ALL"."IX_INSTALMENT_CONFIG_M_DESID" ON "CENTRAL_ALL"."INSTALMENT_CONFIG_M" 
		("DESIG_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "CENTRAL_ALL"."IX_INSTALMENT_CONFIG_M_PROV" ON "CENTRAL_ALL"."INSTALMENT_CONFIG_M" 
		("PROVIENCE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "CENTRAL_ALL"."IX_INSTALMENT_CONFIG_M_RECORDSTATUS" ON "CENTRAL_ALL"."INSTALMENT_CONFIG_M" 
		("RECORD_STATUS" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;
ALTER TABLE "CENTRAL_ALL"."INSTALMENT_CONFIG_M" 
	ADD CONSTRAINT "PK_INSTALMENT_CONFIG" PRIMARY KEY
		("ID") ;

GRANT SELECT ON TABLE "CENTRAL_ALL"."INSTALMENT_CONFIG_M" TO ROLE "ROLE_READ_ONLY"  ;

GRANT SELECT ON TABLE "CENTRAL_ALL"."INSTALMENT_CONFIG_M" TO USER "ETLUSER "  ;

GRANT CONTROL ON TABLE "CENTRAL_ALL"."INSTALMENT_CONFIG_M" TO USER "DB2INST1"  ;
