
CREATE TABLE "CENTRAL_ALL"."LTMISCELLANEOUS_T"  (
		  "ID" VARCHAR(20 OCTETS) NOT NULL , 
		  "REQUEST_ID" VARCHAR(20 OCTETS) , 
		  "CATEGORY_ID" VARCHAR(20 OCTETS) , 
		  "CONSUMER_ID" VARCHAR(20 OCTETS) , 
		  "AMOUNT" DECIMAL(10,2) , 
		  "COLLECTION_DATE" TIMESTAMP(0) , 
		  "PRNO" VARCHAR(30 OCTETS) , 
		  "PAYMENT_MODE_ID" VARCHAR(20 OCTETS) , 
		  "CHEQUE_DD_NUMBER" VARCHAR(30 OCTETS) , 
		  "CHEQUE_DD_DATE" TIMESTAMP(0) , 
		  "CHEQUE_DD_AMOUNT" DECIMAL(10,2) , 
		  "BANK_NAME_ID" VARCHAR(20 OCTETS) , 
		  "REG_NO_ID" VARCHAR(35 OCTETS) , 
		  "CONSUMER_NAME" VARCHAR(100 OCTETS) , 
		  "HOUSE_NO" VARCHAR(30 OCTETS) , 
		  "OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "AREA" VARCHAR(50 OCTETS) , 
		  "DISTRICT" VARCHAR(30 OCTETS) , 
		  "PHONE_NO" VARCHAR(20 OCTETS) , 
		  "CITY" VARCHAR(30 OCTETS) , 
		  "POST_INDICATOR" VARCHAR(1 OCTETS) WITH DEFAULT 'N' , 
		  "POST_DATE" TIMESTAMP(0) , 
		  "CREATED_BY" VARCHAR(10 OCTETS) NOT NULL , 
		  "CREATE_DATE" TIMESTAMP(0) NOT NULL , 
		  "UPDATED_BY" VARCHAR(20 OCTETS) , 
		  "UPDATE_DATE" TIMESTAMP(0) , 
		  "DB_IP_ADDRESS" VARCHAR(25 OCTETS) NOT NULL , 
		  "SOURCE_OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "TARGET_OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "RECORD_STATUS" VARCHAR(10 OCTETS) NOT NULL , 
		  "SCREEN_ID" VARCHAR(30 OCTETS) , 
		  "MONTH" DECFLOAT(16) , 
		  "YEAR" DECFLOAT(16) , 
		  "FLAG_MS" VARCHAR(5 OCTETS) , 
		  "FLAG1" VARCHAR(1 OCTETS) , 
		  "FLAG2" VARCHAR(1 OCTETS) , 
		  "FLAG3" VARCHAR(15 OCTETS) , 
		  "FLAG4" VARCHAR(1 OCTETS) , 
		  "FLAG5" VARCHAR(1 OCTETS) , 
		  "CHECK_CONDITION" VARCHAR(200 OCTETS) NOT NULL , 
		  "MODULE_ID" VARCHAR(30 OCTETS) , 
		  "SUBMODULE_ID" VARCHAR(20 OCTETS) , 
		  "REASON_MODIFY" VARCHAR(100 OCTETS) , 
		  "SACNT_CD" VARCHAR(15 OCTETS) , 
		  "UNIT" VARCHAR(15 OCTETS) , 
		  "LOAD" DECIMAL(10,2) , 
		  "DIVOFFICE" VARCHAR(30 OCTETS) , 
		  "SUBBRANCH" VARCHAR(20 OCTETS) , 
		  "DISP_STATUS" VARCHAR(1 OCTETS) , 
		  "POSTED_DATE" TIMESTAMP(0) , 
		  "CANCELLED_STATUS" VARCHAR(10 OCTETS) , 
		  "CANCELLED_BY" VARCHAR(20 OCTETS) , 
		  "VERIFIED" VARCHAR(20 OCTETS) , 
		  "INITIATED" VARCHAR(20 OCTETS) , 
		  "SUSPECTED" VARCHAR(20 OCTETS) , 
		  "TOKEN_NO" VARCHAR(20 OCTETS) , 
		  "COUNTER_CODE" VARCHAR(5 OCTETS) , 
		  "REMARKS" VARCHAR(150 OCTETS) , 
		  "MOBILE_SERVICE_TRANS_ID" VARCHAR(15 OCTETS) , 
		  "INSTALLMENT_ID" VARCHAR(40 OCTETS) )   
		 IN "TS8"  
		 ORGANIZE BY ROW  ;

CREATE INDEX "CENTRAL_ALL"."IDX_BKNMID_LTMISCELLANEOUS_T" ON "CENTRAL_ALL"."LTMISCELLANEOUS_T" 
		("BANK_NAME_ID" DESC)
		
		COLLECT SAMPLED DETAILED STATISTICS 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "CENTRAL_ALL"."IDX_CHQDDNO_LTMISCELLANEOUS_T" ON "CENTRAL_ALL"."LTMISCELLANEOUS_T" 
		("CHEQUE_DD_NUMBER" DESC)
		
		COLLECT SAMPLED DETAILED STATISTICS 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "CENTRAL_ALL"."IDX_COLDTTR_LTMISCELLANEOUS_T" ON "CENTRAL_ALL"."LTMISCELLANEOUS_T" 
		(TRUNC(COLLECTION_DATE) DESC)
		
		COLLECT SAMPLED DETAILED STATISTICS 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "CENTRAL_ALL"."IDX_COLDT_LTMISCELLANEOUS_T" ON "CENTRAL_ALL"."LTMISCELLANEOUS_T" 
		("COLLECTION_DATE" DESC)
		
		COLLECT SAMPLED DETAILED STATISTICS 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "CENTRAL_ALL"."IDX_CONSID_LTMISCELLANEOUS_T" ON "CENTRAL_ALL"."LTMISCELLANEOUS_T" 
		("CONSUMER_ID" DESC)
		
		COLLECT SAMPLED DETAILED STATISTICS 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "CENTRAL_ALL"."IDX_DISP_STATUS" ON "CENTRAL_ALL"."LTMISCELLANEOUS_T" 
		("DISP_STATUS" ASC)
		PCTFREE 10 
		COLLECT SAMPLED DETAILED STATISTICS 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "CENTRAL_ALL"."IDX_PRNO" ON "CENTRAL_ALL"."LTMISCELLANEOUS_T" 
		("PRNO" ASC)
		PCTFREE 10 
		COLLECT SAMPLED DETAILED STATISTICS 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "CENTRAL_ALL"."IDX_RQID_LTMISCELLANEOUS_T" ON "CENTRAL_ALL"."LTMISCELLANEOUS_T" 
		("REQUEST_ID" DESC)
		
		COLLECT SAMPLED DETAILED STATISTICS 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "CENTRAL_ALL"."IDX_RSTAT_LTMISCELLANEOUS_T" ON "CENTRAL_ALL"."LTMISCELLANEOUS_T" 
		("RECORD_STATUS" DESC)
		
		COLLECT SAMPLED DETAILED STATISTICS 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "CENTRAL_ALL"."IDX_TKNO_LTMISCELLANEOUS_T" ON "CENTRAL_ALL"."LTMISCELLANEOUS_T" 
		("TOKEN_NO" DESC)
		
		COLLECT SAMPLED DETAILED STATISTICS 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;
ALTER TABLE "CENTRAL_ALL"."LTMISCELLANEOUS_T" 
	ADD CONSTRAINT "PK_LTMISCELLANEOUS_T" PRIMARY KEY
		("ID") ;

ALTER TABLE "CENTRAL_ALL"."LTMISCELLANEOUS_T" 
	ADD CONSTRAINT "LTMISCELLANEOUS_T_UK" UNIQUE
		("CHECK_CONDITION") ;
CREATE ALIAS "DABS    "."LTMISCELLANEOUS_T" FOR TABLE "CENTRAL_ALL"."LTMISCELLANEOUS_T" ;
CREATE TRIGGER "CENTRAL_ALL"."TRIG_BRIN_LTMISCELLANEOUS_T"
  NO CASCADE BEFORE INSERT
  ON "CENTRAL_ALL"."LTMISCELLANEOUS_T"
  REFERENCING 
    NEW AS NEW
  FOR EACH ROW
BEGIN ATOMIC



	DECLARE CNT INTEGER;--



	IF (NEW.RECORD_STATUS='ACTIVE') THEN 



		SET NEW.CHECK_CONDITION = NEW.TOKEN_NO||','||TRUNC(NEW.CREATE_DATE);--



	ELSE 



		SET NEW.CHECK_CONDITION = NEW.ID;--



	END IF;--



END ;
CREATE TRIGGER "CENTRAL_ALL"."TRIG_BRUP_LTMISCELLANEOUS_T"
  NO CASCADE BEFORE UPDATE
  ON "CENTRAL_ALL"."LTMISCELLANEOUS_T"
  REFERENCING 
    NEW AS "NEW"
  FOR EACH ROW
BEGIN ATOMIC



	DECLARE CNT INTEGER;--



	IF (NEW.RECORD_STATUS='ACTIVE') THEN 



		SET NEW.CHECK_CONDITION = NEW.TOKEN_NO||','||TRUNC(NEW.CREATE_DATE);--



	ELSE 



		SET NEW.CHECK_CONDITION = NEW.ID;--



	END IF;--



END ;

GRANT SELECT ON TABLE "CENTRAL_ALL"."LTMISCELLANEOUS_T" TO ROLE "ROLE_READ_ONLY"  ;

GRANT SELECT ON TABLE "CENTRAL_ALL"."LTMISCELLANEOUS_T" TO USER "ETLUSER "  ;

GRANT SELECT ON TABLE "CENTRAL_ALL"."LTMISCELLANEOUS_T" TO USER "ZAFAR   "  ;

GRANT CONTROL ON TABLE "CENTRAL_ALL"."LTMISCELLANEOUS_T" TO USER "DB2INST1"  ;
