
CREATE TABLE "CENTRAL_ALL"."PAYMENTS_RECEIVED_CASHIER"  (
		  "ID" VARCHAR(20 OCTETS) NOT NULL , 
		  "AMOUNT_RECEIVED" DECIMAL(10,2) , 
		  "PAYMENT_MODE" VARCHAR(20 OCTETS) , 
		  "COLLECTED_DATE" TIMESTAMP(0) , 
		  "TOTAL_NO" DECIMAL(10,0) , 
		  "RECEIVED_DATE" TIMESTAMP(0) , 
		  "CREATED_BY" VARCHAR(10 OCTETS) NOT NULL , 
		  "CREATE_DATE" TIMESTAMP(0) NOT NULL , 
		  "UPDATED_BY" VARCHAR(20 OCTETS) , 
		  "UPDATE_DATE" TIMESTAMP(0) , 
		  "DB_IP_ADDRESS" VARCHAR(25 OCTETS) NOT NULL , 
		  "SOURCE_OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "TARGET_OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "RECORD_STATUS" VARCHAR(10 OCTETS) NOT NULL , 
		  "SCREEN_ID" VARCHAR(30 OCTETS) , 
		  "MONTH" DECFLOAT(16) NOT NULL , 
		  "YEAR" DECFLOAT(16) NOT NULL , 
		  "FLAG1" VARCHAR(1 OCTETS) , 
		  "FLAG2" VARCHAR(1 OCTETS) , 
		  "FLAG3" VARCHAR(1 OCTETS) , 
		  "FLAG4" VARCHAR(10 OCTETS) , 
		  "FLAG5" VARCHAR(4 OCTETS) , 
		  "CHECK_CONDITION" VARCHAR(30 OCTETS) , 
		  "MODULE_ID" VARCHAR(20 OCTETS) , 
		  "SUBMODULE_ID" VARCHAR(20 OCTETS) , 
		  "COUNTER_ID" VARCHAR(20 OCTETS) )   
		 IN "TS8"  
		 ORGANIZE BY ROW  ;
ALTER TABLE "CENTRAL_ALL"."PAYMENTS_RECEIVED_CASHIER" 
	ADD CONSTRAINT "PAYMENTS_RECEIVED_CASHIER_PK" PRIMARY KEY
		("ID") ;

GRANT SELECT ON TABLE "CENTRAL_ALL"."PAYMENTS_RECEIVED_CASHIER" TO ROLE "ROLE_READ_ONLY"  ;

GRANT SELECT ON TABLE "CENTRAL_ALL"."PAYMENTS_RECEIVED_CASHIER" TO USER "ETLUSER "  ;

GRANT SELECT ON TABLE "CENTRAL_ALL"."PAYMENTS_RECEIVED_CASHIER" TO USER "ZAFAR   "  ;

GRANT CONTROL ON TABLE "CENTRAL_ALL"."PAYMENTS_RECEIVED_CASHIER" TO USER "DB2INST1"  ;
