-- DB2INST1.ADJ_ID definition

CREATE TABLE "DB2INST1"."ADJ_ID"  (
		  "MTR_ID" VARCHAR(20 OCTETS) )   
		 IN "TS8"  
		 ORGANIZE BY ROW  ;

GRANT CONTROL ON TABLE "DB2INST1"."ADJ_ID" TO USER "DB2INST1"  ;


-- DB2INST1.CMTCONSUMER_M_BACK definition

CREATE TABLE "DB2INST1"."CMTCONSUMER_M_BACK"  (
		  "ID" VARCHAR(40 OCTETS) NOT NULL , 
		  "SCNO" VARCHAR(25 OCTETS) NOT NULL , 
		  "OLD_SCNO" VARCHAR(25 OCTETS) , 
		  "NAME" VARCHAR(300 OCTETS) NOT NULL , 
		  "FATHER_NAME" VARCHAR(100 OCTETS) , 
		  "GFATHER_NAME" VARCHAR(100 OCTETS) , 
		  "ADDRESS_1" VARCHAR(500 OCTETS) , 
		  "ADDRESS_2" VARCHAR(50 OCTETS) , 
		  "ADDRESS_3" VARCHAR(50 OCTETS) , 
		  "ADDRESS_4" VARCHAR(50 OCTETS) , 
		  "PHONE" VARCHAR(30 OCTETS) , 
		  "EMAIL" VARCHAR(30 OCTETS) , 
		  "HOUSE_OWNER_NAME" VARCHAR(100 OCTETS) , 
		  "HOUSE_OWNER_FNAME" VARCHAR(100 OCTETS) , 
		  "AREA_CODE" VARCHAR(30 OCTETS) , 
		  "ROUTE" VARCHAR(30 OCTETS) , 
		  "OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "CATEGORY" VARCHAR(15 OCTETS) , 
		  "SUB_CATEGORY" VARCHAR(25 OCTETS) , 
		  "PHASE" VARCHAR(15 OCTETS) , 
		  "CONTRACTED_LOAD" DECIMAL(13,5) , 
		  "CONNECTED_LOAD" DECIMAL(13,5) , 
		  "LOAD_UNIT" VARCHAR(15 OCTETS) , 
		  "LOAD_TYPE" VARCHAR(5 OCTETS) , 
		  "NATURE_OF_PREMISES" VARCHAR(20 OCTETS) , 
		  "SUPP_RELEASE_DATE" TIMESTAMP NOT NULL , 
		  "SERVICE_STATUS" VARCHAR(5 OCTETS) , 
		  "CONSUMER_STATUS" VARCHAR(6 OCTETS) , 
		  "CONSUMER_TYPE" VARCHAR(10 OCTETS) , 
		  "POL_NUM" VARCHAR(200 OCTETS) , 
		  "TRANS_LOCATION" VARCHAR(30 OCTETS) , 
		  "FEEDER_NUM" VARCHAR(20 OCTETS) , 
		  "SUBSTATION_NUM" VARCHAR(15 OCTETS) , 
		  "ALTERNATE_ADDRESS_1" VARCHAR(50 OCTETS) , 
		  "ALTERNATE_ADDRESS_2" VARCHAR(50 OCTETS) , 
		  "ALTERNATE_ADDRESS_3" VARCHAR(50 OCTETS) , 
		  "ALTERNATE_ADDRESS_4" VARCHAR(30 OCTETS) , 
		  "BILLING_CYCLE" DECIMAL(2,0) , 
		  "SHORT_NAME" VARCHAR(50 OCTETS) , 
		  "AGREEMENT_DATE" TIMESTAMP , 
		  "LIGHTING_LOAD" DECIMAL(10,2) , 
		  "TOWNSHIP_LOAD" DECIMAL(15,2) , 
		  "TR_HIRE_CHARGES" DECIMAL(15,2) , 
		  "NO_OF_FEEDERS" DECIMAL(2,0) , 
		  "ADDL_TEMP_LOAD" VARCHAR(5 OCTETS) , 
		  "SUPPLY_VOLTAGE" VARCHAR(15 OCTETS) , 
		  "VOLTAGE_UNIT" VARCHAR(10 OCTETS) , 
		  "CONSTRUCTION_TYPE" VARCHAR(25 OCTETS) , 
		  "CREATED_BY" VARCHAR(20 OCTETS) NOT NULL , 
		  "CREATE_DATE" TIMESTAMP , 
		  "UPDATED_BY" VARCHAR(20 OCTETS) , 
		  "UPDATE_DATE" TIMESTAMP , 
		  "DB_IP_ADDRESS" VARCHAR(20 OCTETS) NOT NULL , 
		  "SOURCE_OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "TARGET_OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "RECORD_STATUS" VARCHAR(10 OCTETS) NOT NULL , 
		  "SCREEN_ID" VARCHAR(30 OCTETS) NOT NULL , 
		  "MONTH" DECIMAL(5,0) , 
		  "YEAR" DECIMAL(5,0) , 
		  "FLAG1" VARCHAR(20 OCTETS) , 
		  "FLAG2" VARCHAR(10 OCTETS) , 
		  "FLAG3" VARCHAR(1 OCTETS) , 
		  "FLAG4" VARCHAR(20 OCTETS) , 
		  "FLAG5" VARCHAR(15 OCTETS) , 
		  "MODULE_ID" VARCHAR(20 OCTETS) , 
		  "SUBMODULE_ID" VARCHAR(20 OCTETS) , 
		  "CHECK_CONDITION" VARCHAR(40 OCTETS) , 
		  "CAPACITOR_AVAIL" VARCHAR(1 OCTETS) , 
		  "METER_OWNERSHIP" VARCHAR(15 OCTETS) , 
		  "SBRNCH_CD" VARCHAR(15 OCTETS) , 
		  "CREDIT_HISTORY" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N' , 
		  "CHEQUEBOUNCE_DATE" TIMESTAMP , 
		  "CHEQUEBOUNCE_REASON" VARCHAR(100 OCTETS) , 
		  "DEBT_FLAG" VARCHAR(1 OCTETS) , 
		  "DEBT_ACTION_FLAG" VARCHAR(1 OCTETS) , 
		  "ALLOWEDCHKCNT" DECIMAL(10,0) , 
		  "ACCOUNT_NO" VARCHAR(20 OCTETS) NOT NULL , 
		  "CONSUMER_ID" VARCHAR(25 OCTETS) , 
		  "COUNTRY_ID" VARCHAR(20 OCTETS) , 
		  "METERINGPOINT" VARCHAR(4 OCTETS) , 
		  "CONNECTIONEXPIREDATE" TIMESTAMP , 
		  "APPROVEDPOWERFACTOR" DECIMAL(6,3) , 
		  "SERVICEREGION" VARCHAR(7 OCTETS) WITH DEFAULT 'Inner' , 
		  "ISCONSUMEROPTEDTOD" VARCHAR(1 OCTETS) , 
		  "NEXTBILLINGDATE" TIMESTAMP , 
		  "BILLING_STATUS" VARCHAR(1 OCTETS) , 
		  "SCHEDULE_DAY" DECIMAL(2,0) , 
		  "GEN_SCNO" VARCHAR(25 OCTETS) NOT NULL , 
		  "ADDRESS_5" VARCHAR(30 OCTETS) , 
		  "ALTERNATE_ADDRESS_5" VARCHAR(30 OCTETS) , 
		  "EFFECT_DATE" TIMESTAMP , 
		  "ROUTE_ID" VARCHAR(30 OCTETS) , 
		  "MR_APPLICABLE_FLAG" VARCHAR(1 OCTETS) , 
		  "METER_RENT" DECIMAL(28,0) , 
		  "SUBMETER_COUNT" DECFLOAT(16) , 
		  "CONN_BY" VARCHAR(20 OCTETS) , 
		  "LEVEL_ID" VARCHAR(1 OCTETS) , 
		  "BILLFLG" DECIMAL(1,0) WITH DEFAULT 0 , 
		  "DEMAND_METER_FLAG" VARCHAR(2 OCTETS) WITH DEFAULT 3 , 
		  "DEMAND" DECIMAL(13,5) , 
		  "MTRNO" VARCHAR(20 OCTETS) WITH DEFAULT 0 , 
		  "MF_KWH" DECIMAL(10,2) WITH DEFAULT 0 , 
		  "GOVTCODE_ID" VARCHAR(20 OCTETS) , 
		  "NOOFMONTHS_METERRENT" DECFLOAT(16) WITH DEFAULT 0 , 
		  "BILLMONTH" DECFLOAT(16) , 
		  "BILLYEAR" DECFLOAT(16) , 
		  "ETISALAT_ID" VARCHAR(20 OCTETS) , 
		  "TESTCOL" VARCHAR(20 OCTETS) , 
		  "LANDMARKS" VARCHAR(300 OCTETS) , 
		  "IS_GOVT_SUBSIDY" CHAR(2 OCTETS) , 
		  "GOVT_SUBSIDY" DECIMAL(20,3) , 
		  "DC_APP_FLG" VARCHAR(1 OCTETS) , 
		  "GISUID" VARCHAR(25 OCTETS) , 
		  "DIESEL_CHG" DECIMAL(10,2) , 
		  "PIN_NO" DECIMAL(10,5) , 
		  "PRIORITY" VARCHAR(20 OCTETS) , 
		  "BOOKNO" VARCHAR(50 OCTETS) , 
		  "GIS_LAT" DECIMAL(25,10) , 
		  "GIS_LONG" DECIMAL(25,10) , 
		  "CHQ_REJ_MONTHS" VARCHAR(2 OCTETS) , 
		  "SET1" VARCHAR(3 OCTETS) , 
		  "MOHALLANO" VARCHAR(7 OCTETS) , 
		  "GEOCODE" VARCHAR(18 OCTETS) , 
		  "METERING_VOLT" DECIMAL(15,5) , 
		  "FLORICARE_FLAG" VARCHAR(1 OCTETS) , 
		  "POWER_LOOM_FLAG" VARCHAR(1 OCTETS) , 
		  "MET_DOM_LMV1_FLAG" VARCHAR(1 OCTETS) , 
		  "RURAL_FEEDER_FLAG" VARCHAR(1 OCTETS) , 
		  "GOVT_CODE_ID" VARCHAR(10 OCTETS) , 
		  "BILLBASIS" VARCHAR(10 OCTETS) , 
		  "PERMANENT_ADDRESS_1" VARCHAR(50 OCTETS) , 
		  "PERMANENT_ADDRESS_2" VARCHAR(50 OCTETS) , 
		  "PERMANENT_ADDRESS_3" VARCHAR(50 OCTETS) , 
		  "METRIC" VARCHAR(30 OCTETS) , 
		  "ABADI" VARCHAR(30 OCTETS) , 
		  "VOLT_ID" VARCHAR(20 OCTETS) , 
		  "COMPOUND_STATUS" VARCHAR(2 OCTETS) , 
		  "PERMANENT_ADDRESS_4" VARCHAR(50 OCTETS) , 
		  "PERMANENT_ADDRESS_5" VARCHAR(50 OCTETS) , 
		  "INITIAL_ARRAMT" DECIMAL(10,2) , 
		  "BINDER_NO" VARCHAR(20 OCTETS) , 
		  "BINDER_PAGE_NO" VARCHAR(20 OCTETS) , 
		  "LOCATION_TYPE" VARCHAR(1 OCTETS) , 
		  "TYPE_SWITCH" VARCHAR(1 OCTETS) , 
		  "IS_ROUNDCLOCK_SUP" VARCHAR(1 OCTETS) , 
		  "IS_SWH_EXISTS" VARCHAR(1 OCTETS) , 
		  "DISTRICT" VARCHAR(25 OCTETS) , 
		  "TOWN" VARCHAR(25 OCTETS) , 
		  "VILLAGE" VARCHAR(25 OCTETS) , 
		  "BA_DISTRICT" VARCHAR(50 OCTETS) , 
		  "BA_TOWN" VARCHAR(25 OCTETS) , 
		  "BA_VILLAGE" VARCHAR(25 OCTETS) , 
		  "PA_DISTRICT" VARCHAR(25 OCTETS) , 
		  "PA_TOWN" VARCHAR(25 OCTETS) , 
		  "PA_VILLAGE" VARCHAR(25 OCTETS) , 
		  "SUBGROUP" VARCHAR(10 OCTETS) , 
		  "GRP" VARCHAR(10 OCTETS) , 
		  "METER_REQUIRED" VARCHAR(10 OCTETS) , 
		  "RETURN_MONTH" VARCHAR(7 OCTETS) , 
		  "DLIST_STATUS" VARCHAR(8 OCTETS) , 
		  "MTR_RDG_CHNG" VARCHAR(15 OCTETS) , 
		  "NEXT_BILLINGDT" TIMESTAMP , 
		  "ISBILLED" VARCHAR(2 OCTETS) , 
		  "DEDICATED_FLAG" VARCHAR(1 OCTETS) , 
		  "TRANSFORMER_CAPACITY" VARCHAR(20 OCTETS) )   
		 IN "TS8"  
		 ORGANIZE BY ROW  ;

GRANT SELECT ON TABLE "DB2INST1"."CMTCONSUMER_M_BACK" TO ROLE "ROLE_READ_ONLY"  ;

GRANT CONTROL ON TABLE "DB2INST1"."CMTCONSUMER_M_BACK" TO USER "DB2INST1"  ;


-- DB2INST1.CMTCONSUMER_M_UP definition

CREATE TABLE "DB2INST1"."CMTCONSUMER_M_UP"  (
		  "ID" VARCHAR(40 OCTETS) NOT NULL , 
		  "SCNO" VARCHAR(25 OCTETS) NOT NULL , 
		  "OLD_SCNO" VARCHAR(25 OCTETS) , 
		  "NAME" VARCHAR(300 OCTETS) NOT NULL , 
		  "FATHER_NAME" VARCHAR(100 OCTETS) , 
		  "GFATHER_NAME" VARCHAR(100 OCTETS) , 
		  "ADDRESS_1" VARCHAR(500 OCTETS) , 
		  "ADDRESS_2" VARCHAR(50 OCTETS) , 
		  "ADDRESS_3" VARCHAR(50 OCTETS) , 
		  "ADDRESS_4" VARCHAR(50 OCTETS) , 
		  "PHONE" VARCHAR(30 OCTETS) , 
		  "EMAIL" VARCHAR(30 OCTETS) , 
		  "HOUSE_OWNER_NAME" VARCHAR(100 OCTETS) , 
		  "HOUSE_OWNER_FNAME" VARCHAR(100 OCTETS) , 
		  "AREA_CODE" VARCHAR(30 OCTETS) , 
		  "ROUTE" VARCHAR(30 OCTETS) , 
		  "OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "CATEGORY" VARCHAR(15 OCTETS) , 
		  "SUB_CATEGORY" VARCHAR(25 OCTETS) , 
		  "PHASE" VARCHAR(15 OCTETS) , 
		  "CONTRACTED_LOAD" DECIMAL(13,5) , 
		  "CONNECTED_LOAD" DECIMAL(13,5) , 
		  "LOAD_UNIT" VARCHAR(15 OCTETS) , 
		  "LOAD_TYPE" VARCHAR(5 OCTETS) , 
		  "NATURE_OF_PREMISES" VARCHAR(20 OCTETS) , 
		  "SUPP_RELEASE_DATE" TIMESTAMP NOT NULL , 
		  "SERVICE_STATUS" VARCHAR(5 OCTETS) , 
		  "CONSUMER_STATUS" VARCHAR(6 OCTETS) , 
		  "CONSUMER_TYPE" VARCHAR(10 OCTETS) , 
		  "POL_NUM" VARCHAR(200 OCTETS) , 
		  "TRANS_LOCATION" VARCHAR(30 OCTETS) , 
		  "FEEDER_NUM" VARCHAR(20 OCTETS) , 
		  "SUBSTATION_NUM" VARCHAR(15 OCTETS) , 
		  "ALTERNATE_ADDRESS_1" VARCHAR(50 OCTETS) , 
		  "ALTERNATE_ADDRESS_2" VARCHAR(50 OCTETS) , 
		  "ALTERNATE_ADDRESS_3" VARCHAR(50 OCTETS) , 
		  "ALTERNATE_ADDRESS_4" VARCHAR(30 OCTETS) , 
		  "BILLING_CYCLE" DECIMAL(2,0) , 
		  "SHORT_NAME" VARCHAR(50 OCTETS) , 
		  "AGREEMENT_DATE" TIMESTAMP , 
		  "LIGHTING_LOAD" DECIMAL(10,2) , 
		  "TOWNSHIP_LOAD" DECIMAL(15,2) , 
		  "TR_HIRE_CHARGES" DECIMAL(15,2) , 
		  "NO_OF_FEEDERS" DECIMAL(2,0) , 
		  "ADDL_TEMP_LOAD" VARCHAR(5 OCTETS) , 
		  "SUPPLY_VOLTAGE" VARCHAR(15 OCTETS) , 
		  "VOLTAGE_UNIT" VARCHAR(10 OCTETS) , 
		  "CONSTRUCTION_TYPE" VARCHAR(25 OCTETS) , 
		  "CREATED_BY" VARCHAR(20 OCTETS) NOT NULL , 
		  "CREATE_DATE" TIMESTAMP , 
		  "UPDATED_BY" VARCHAR(20 OCTETS) , 
		  "UPDATE_DATE" TIMESTAMP , 
		  "DB_IP_ADDRESS" VARCHAR(20 OCTETS) NOT NULL , 
		  "SOURCE_OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "TARGET_OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "RECORD_STATUS" VARCHAR(10 OCTETS) NOT NULL , 
		  "SCREEN_ID" VARCHAR(30 OCTETS) NOT NULL , 
		  "MONTH" DECIMAL(5,0) , 
		  "YEAR" DECIMAL(5,0) , 
		  "FLAG1" VARCHAR(20 OCTETS) , 
		  "FLAG2" VARCHAR(10 OCTETS) , 
		  "FLAG3" VARCHAR(1 OCTETS) , 
		  "FLAG4" VARCHAR(20 OCTETS) , 
		  "FLAG5" VARCHAR(15 OCTETS) , 
		  "MODULE_ID" VARCHAR(20 OCTETS) , 
		  "SUBMODULE_ID" VARCHAR(20 OCTETS) , 
		  "CHECK_CONDITION" VARCHAR(40 OCTETS) , 
		  "CAPACITOR_AVAIL" VARCHAR(1 OCTETS) , 
		  "METER_OWNERSHIP" VARCHAR(15 OCTETS) , 
		  "SBRNCH_CD" VARCHAR(15 OCTETS) , 
		  "CREDIT_HISTORY" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N' , 
		  "CHEQUEBOUNCE_DATE" TIMESTAMP , 
		  "CHEQUEBOUNCE_REASON" VARCHAR(100 OCTETS) , 
		  "DEBT_FLAG" VARCHAR(1 OCTETS) , 
		  "DEBT_ACTION_FLAG" VARCHAR(1 OCTETS) , 
		  "ALLOWEDCHKCNT" DECIMAL(10,0) , 
		  "ACCOUNT_NO" VARCHAR(20 OCTETS) NOT NULL , 
		  "CONSUMER_ID" VARCHAR(25 OCTETS) , 
		  "COUNTRY_ID" VARCHAR(20 OCTETS) , 
		  "METERINGPOINT" VARCHAR(4 OCTETS) , 
		  "CONNECTIONEXPIREDATE" TIMESTAMP , 
		  "APPROVEDPOWERFACTOR" DECIMAL(6,3) , 
		  "SERVICEREGION" VARCHAR(7 OCTETS) WITH DEFAULT 'Inner' , 
		  "ISCONSUMEROPTEDTOD" VARCHAR(1 OCTETS) , 
		  "NEXTBILLINGDATE" TIMESTAMP , 
		  "BILLING_STATUS" VARCHAR(1 OCTETS) , 
		  "SCHEDULE_DAY" DECIMAL(2,0) , 
		  "GEN_SCNO" VARCHAR(25 OCTETS) NOT NULL , 
		  "ADDRESS_5" VARCHAR(30 OCTETS) , 
		  "ALTERNATE_ADDRESS_5" VARCHAR(30 OCTETS) , 
		  "EFFECT_DATE" TIMESTAMP , 
		  "ROUTE_ID" VARCHAR(30 OCTETS) , 
		  "MR_APPLICABLE_FLAG" VARCHAR(1 OCTETS) , 
		  "METER_RENT" DECIMAL(28,0) , 
		  "SUBMETER_COUNT" DECFLOAT(16) , 
		  "CONN_BY" VARCHAR(20 OCTETS) , 
		  "LEVEL_ID" VARCHAR(1 OCTETS) , 
		  "BILLFLG" DECIMAL(1,0) WITH DEFAULT 0 , 
		  "DEMAND_METER_FLAG" VARCHAR(2 OCTETS) WITH DEFAULT 3 , 
		  "DEMAND" DECIMAL(13,5) , 
		  "MTRNO" VARCHAR(20 OCTETS) WITH DEFAULT 0 , 
		  "MF_KWH" DECIMAL(10,2) WITH DEFAULT 0 , 
		  "GOVTCODE_ID" VARCHAR(20 OCTETS) , 
		  "NOOFMONTHS_METERRENT" DECFLOAT(16) WITH DEFAULT 0 , 
		  "BILLMONTH" DECFLOAT(16) , 
		  "BILLYEAR" DECFLOAT(16) , 
		  "ETISALAT_ID" VARCHAR(20 OCTETS) , 
		  "TESTCOL" VARCHAR(20 OCTETS) , 
		  "LANDMARKS" VARCHAR(300 OCTETS) , 
		  "IS_GOVT_SUBSIDY" CHAR(2 OCTETS) , 
		  "GOVT_SUBSIDY" DECIMAL(20,3) , 
		  "DC_APP_FLG" VARCHAR(1 OCTETS) , 
		  "GISUID" VARCHAR(25 OCTETS) , 
		  "DIESEL_CHG" DECIMAL(10,2) , 
		  "PIN_NO" DECIMAL(10,5) , 
		  "PRIORITY" VARCHAR(20 OCTETS) , 
		  "BOOKNO" VARCHAR(50 OCTETS) , 
		  "GIS_LAT" DECIMAL(25,10) , 
		  "GIS_LONG" DECIMAL(25,10) , 
		  "CHQ_REJ_MONTHS" VARCHAR(2 OCTETS) , 
		  "SET1" VARCHAR(3 OCTETS) , 
		  "MOHALLANO" VARCHAR(7 OCTETS) , 
		  "GEOCODE" VARCHAR(18 OCTETS) , 
		  "METERING_VOLT" DECIMAL(15,5) , 
		  "FLORICARE_FLAG" VARCHAR(1 OCTETS) , 
		  "POWER_LOOM_FLAG" VARCHAR(1 OCTETS) , 
		  "MET_DOM_LMV1_FLAG" VARCHAR(1 OCTETS) , 
		  "RURAL_FEEDER_FLAG" VARCHAR(1 OCTETS) , 
		  "GOVT_CODE_ID" VARCHAR(10 OCTETS) , 
		  "BILLBASIS" VARCHAR(10 OCTETS) , 
		  "PERMANENT_ADDRESS_1" VARCHAR(50 OCTETS) , 
		  "PERMANENT_ADDRESS_2" VARCHAR(50 OCTETS) , 
		  "PERMANENT_ADDRESS_3" VARCHAR(50 OCTETS) , 
		  "METRIC" VARCHAR(30 OCTETS) , 
		  "ABADI" VARCHAR(30 OCTETS) , 
		  "VOLT_ID" VARCHAR(20 OCTETS) , 
		  "COMPOUND_STATUS" VARCHAR(2 OCTETS) , 
		  "PERMANENT_ADDRESS_4" VARCHAR(50 OCTETS) , 
		  "PERMANENT_ADDRESS_5" VARCHAR(50 OCTETS) , 
		  "INITIAL_ARRAMT" DECIMAL(10,2) , 
		  "BINDER_NO" VARCHAR(20 OCTETS) , 
		  "BINDER_PAGE_NO" VARCHAR(20 OCTETS) , 
		  "LOCATION_TYPE" VARCHAR(1 OCTETS) , 
		  "TYPE_SWITCH" VARCHAR(1 OCTETS) , 
		  "IS_ROUNDCLOCK_SUP" VARCHAR(1 OCTETS) , 
		  "IS_SWH_EXISTS" VARCHAR(1 OCTETS) , 
		  "DISTRICT" VARCHAR(25 OCTETS) , 
		  "TOWN" VARCHAR(25 OCTETS) , 
		  "VILLAGE" VARCHAR(25 OCTETS) , 
		  "BA_DISTRICT" VARCHAR(50 OCTETS) , 
		  "BA_TOWN" VARCHAR(25 OCTETS) , 
		  "BA_VILLAGE" VARCHAR(25 OCTETS) , 
		  "PA_DISTRICT" VARCHAR(25 OCTETS) , 
		  "PA_TOWN" VARCHAR(25 OCTETS) , 
		  "PA_VILLAGE" VARCHAR(25 OCTETS) , 
		  "SUBGROUP" VARCHAR(10 OCTETS) , 
		  "GRP" VARCHAR(10 OCTETS) , 
		  "METER_REQUIRED" VARCHAR(10 OCTETS) , 
		  "RETURN_MONTH" VARCHAR(7 OCTETS) , 
		  "DLIST_STATUS" VARCHAR(8 OCTETS) , 
		  "MTR_RDG_CHNG" VARCHAR(15 OCTETS) , 
		  "NEXT_BILLINGDT" TIMESTAMP , 
		  "ISBILLED" VARCHAR(2 OCTETS) , 
		  "DEDICATED_FLAG" VARCHAR(1 OCTETS) , 
		  "TRANSFORMER_CAPACITY" VARCHAR(20 OCTETS) )   
		 IN "TS8"  
		 ORGANIZE BY ROW  ;

GRANT SELECT ON TABLE "DB2INST1"."CMTCONSUMER_M_UP" TO ROLE "ROLE_READ_ONLY"  ;

GRANT CONTROL ON TABLE "DB2INST1"."CMTCONSUMER_M_UP" TO USER "DB2INST1"  ;


-- DB2INST1.CSTNEWREG_FEE_DT_BACKUP definition

CREATE TABLE "DB2INST1"."CSTNEWREG_FEE_DT_BACKUP"  (
		  "ID" VARCHAR(20 OCTETS) NOT NULL , 
		  "REGISTRATION_ID" VARCHAR(20 OCTETS) , 
		  "REQUEST_ID" VARCHAR(20 OCTETS) , 
		  "FEE_TYPE_ID" VARCHAR(20 OCTETS) , 
		  "FEE" DECIMAL(15,2) , 
		  "PAY_FLAG" VARCHAR(1 OCTETS) WITH DEFAULT 'N' , 
		  "CREATED_BY" VARCHAR(20 OCTETS) NOT NULL , 
		  "CREATE_DATE" TIMESTAMP(0) NOT NULL , 
		  "UPDATED_BY" VARCHAR(20 OCTETS) , 
		  "UPDATE_DATE" TIMESTAMP(0) , 
		  "DB_IP_ADDRESS" VARCHAR(25 OCTETS) NOT NULL , 
		  "SOURCE_OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "TARGET_OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "RECORD_STATUS" VARCHAR(10 OCTETS) NOT NULL , 
		  "SCREEN_ID" VARCHAR(30 OCTETS) NOT NULL , 
		  "MONTH" DECFLOAT(16) NOT NULL , 
		  "YEAR" DECFLOAT(16) NOT NULL , 
		  "FLAG1" VARCHAR(1 OCTETS) , 
		  "FLAG2" VARCHAR(1 OCTETS) , 
		  "FLAG3" VARCHAR(1 OCTETS) , 
		  "FLAG4" VARCHAR(1 OCTETS) , 
		  "FLAG5" VARCHAR(1 OCTETS) , 
		  "CHECK_CONDITION" VARCHAR(40 OCTETS) , 
		  "MODULE_ID" VARCHAR(20 OCTETS) , 
		  "SUBMODULE_ID" VARCHAR(20 OCTETS) , 
		  "FEE_PAID" DECIMAL(15,2) )   
		 IN "TS8"  
		 ORGANIZE BY ROW  ;

GRANT SELECT ON TABLE "DB2INST1"."CSTNEWREG_FEE_DT_BACKUP" TO ROLE "ROLE_READ_ONLY"  ;

GRANT CONTROL ON TABLE "DB2INST1"."CSTNEWREG_FEE_DT_BACKUP" TO USER "DB2INST1"  ;


-- DB2INST1.CSTREQUEST_T_BACKUP definition

CREATE TABLE "DB2INST1"."CSTREQUEST_T_BACKUP"  (
		  "ID" VARCHAR(20 OCTETS) NOT NULL , 
		  "REGISTRATION_NO" VARCHAR(20 OCTETS) , 
		  "CONSUMER_ID" VARCHAR(20 OCTETS) , 
		  "COMPLAINANT_NAME" VARCHAR(100 OCTETS) , 
		  "REQUESTNATURE_ID" VARCHAR(20 OCTETS) , 
		  "COMPLAINANT_DOOR_NO" VARCHAR(200 OCTETS) , 
		  "COMPLAINANT_STREET" VARCHAR(100 OCTETS) , 
		  "COMPLAINANT_AREA" VARCHAR(100 OCTETS) , 
		  "COMPLAINANT_CITY" VARCHAR(100 OCTETS) , 
		  "COMPLAINANT_PINCODE" VARCHAR(30 OCTETS) , 
		  "COMPLAINANT_LAND_MARKS" VARCHAR(500 OCTETS) , 
		  "COMPLAINANT_PHONE" VARCHAR(20 OCTETS) , 
		  "COMPLAINANT_FAX" VARCHAR(100 OCTETS) , 
		  "COMPLAINANT_EMAIL" VARCHAR(100 OCTETS) , 
		  "REQUEST_DETAILS" VARCHAR(300 OCTETS) , 
		  "PRIORITY" DECFLOAT(16) , 
		  "ORIGIN" DECFLOAT(16) , 
		  "STATUS" DECFLOAT(16) , 
		  "WAIT_FOR_PAYMENT" CHAR(1 OCTETS) WITH DEFAULT 'N' , 
		  "SERVICE_ORDER_NO" VARCHAR(20 OCTETS) , 
		  "OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "ALLOCATED_TO" VARCHAR(30 OCTETS) , 
		  "ALLOCATED_ON" TIMESTAMP(0) , 
		  "NEXT_FOLLOW_UP_TIME" TIMESTAMP(0) , 
		  "TO_BE_RECTIFIED_ON" TIMESTAMP(0) , 
		  "FIRST_ESCALATION_ON" TIMESTAMP(0) , 
		  "FIRST_ESCALATIONTO_ID" VARCHAR(20 OCTETS) , 
		  "SECOND_ESCALATION_ON" TIMESTAMP(0) , 
		  "SECOND_ESCALATIONTO_ID" VARCHAR(20 OCTETS) , 
		  "RESPONSIBLEPERSON_ID" VARCHAR(20 OCTETS) , 
		  "ESCALATION_DETAILS" VARCHAR(300 OCTETS) , 
		  "PR_NO" VARCHAR(30 OCTETS) , 
		  "RECTIFIED_ON" TIMESTAMP(0) , 
		  "RECTIFIED_BY" VARCHAR(20 OCTETS) , 
		  "REQUEST_REGISTERED_ON" TIMESTAMP(0) NOT NULL , 
		  "REQUEST_REGISTERED_BY" VARCHAR(20 OCTETS) , 
		  "ACKNOWLEDGED_BY" VARCHAR(30 OCTETS) , 
		  "ACKNOWLEDGED_ON" TIMESTAMP(0) , 
		  "IS_ON_HOLD" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N' , 
		  "REASON_FOR_HOLD" VARCHAR(300 OCTETS) , 
		  "ACTION_TAKEN" VARCHAR(300 OCTETS) , 
		  "CONSUMER_REMARKS" VARCHAR(300 OCTETS) , 
		  "CREATE_DATE" TIMESTAMP(0) NOT NULL , 
		  "CREATED_BY" VARCHAR(20 OCTETS) NOT NULL , 
		  "UPDATED_BY" VARCHAR(20 OCTETS) , 
		  "UPDATE_DATE" TIMESTAMP(0) , 
		  "DB_IP_ADDRESS" VARCHAR(25 OCTETS) NOT NULL , 
		  "SOURCE_OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "TARGET_OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "RECORD_STATUS" VARCHAR(10 OCTETS) NOT NULL , 
		  "SCREEN_ID" VARCHAR(30 OCTETS) NOT NULL , 
		  "MONTH" DECFLOAT(16) NOT NULL , 
		  "YEAR" DECFLOAT(16) NOT NULL , 
		  "FLAG1" VARCHAR(5 OCTETS) , 
		  "FLAG2" VARCHAR(8 OCTETS) , 
		  "FLAG3" VARCHAR(1 OCTETS) , 
		  "FLAG4" VARCHAR(5 OCTETS) , 
		  "CHECK_CONDITION" VARCHAR(20 OCTETS) NOT NULL , 
		  "TO_BE_INSPECTED_ON" TIMESTAMP(0) , 
		  "ACTUAL_INSPECTED_DT" TIMESTAMP(0) , 
		  "FORWARDED_ON" TIMESTAMP(0) , 
		  "PAYMENT_MODE" VARCHAR(15 OCTETS) , 
		  "PAYMENT_AMOUNT" DECIMAL(10,2) , 
		  "PAYMENT_DUE_DATE" TIMESTAMP(0) , 
		  "REASON_FOR_PAYMENT" VARCHAR(300 OCTETS) , 
		  "PAYMENT_MADE_ON" TIMESTAMP(0) , 
		  "REASON_FOR_PENDING" VARCHAR(300 OCTETS) , 
		  "MODULE_ID" VARCHAR(20 OCTETS) , 
		  "SUBMODULE_ID" VARCHAR(20 OCTETS) , 
		  "ACTUAL_REC_DATE" TIMESTAMP(0) , 
		  "ACTUAL_INV_DATE" TIMESTAMP(0) , 
		  "REFERENCE_NO" VARCHAR(20 OCTETS) , 
		  "APP_FEE" DECIMAL(10,2) , 
		  "REASON_MODIFICATION" VARCHAR(100 OCTETS) , 
		  "DISPATCH_LETTER_NO" VARCHAR(10 OCTETS) , 
		  "NO_OF_HOLIDAYS" DECIMAL(2,0) , 
		  "REFUND_AMT" DECIMAL(10,2) , 
		  "LOAD_CHANGE" DECIMAL(10,2) , 
		  "UNIT_CHANGE" VARCHAR(15 OCTETS) , 
		  "SC_CH" DECIMAL(10,2) , 
		  "OTH_CH" DECIMAL(10,2) , 
		  "CONSUMER_CHANGES" VARCHAR(1 OCTETS) , 
		  "RESPONSIBLEPERSON_SHOW" VARCHAR(20 OCTETS) , 
		  "APPROVED_PER" VARCHAR(20 OCTETS) , 
		  "REFUND_DD" VARCHAR(30 OCTETS) , 
		  "REFUND_DATE" TIMESTAMP(0) , 
		  "COMPLAINANT_VILLAGE" VARCHAR(50 OCTETS) , 
		  "IS_METER_CHANGE_REQ" VARCHAR(1 OCTETS) , 
		  "METER_CHANGE_PHASE" VARCHAR(1 OCTETS) , 
		  "IS_CONS_PAY_REQ" VARCHAR(1 OCTETS) , 
		  "PAY_TYPE" VARCHAR(10 OCTETS) , 
		  "METER_TYPE" VARCHAR(10 OCTETS) , 
		  "FAULT_TYPE" VARCHAR(10 OCTETS) , 
		  "FEASIBILITY" VARCHAR(25 OCTETS) , 
		  "DISPATCH_FLAG" VARCHAR(5 OCTETS) , 
		  "FINAL_READING" VARCHAR(10 OCTETS) , 
		  "SETTLEMENT_AMT" DECIMAL(10,2) , 
		  "SETTLEMENTOFFICE_ID" VARCHAR(20 OCTETS) , 
		  "REGESTERED_AT" VARCHAR(20 OCTETS) , 
		  "SETTLEMENT_DT" TIMESTAMP(0) , 
		  "SETTLED_AMOUNT" DECIMAL(10,2) , 
		  "DECISION" VARCHAR(60 OCTETS) , 
		  "CONSUMER_SATIFICATION" VARCHAR(1 OCTETS) , 
		  "CCAR_FLAG" VARCHAR(3 OCTETS) , 
		  "RECONN_CHG" DECIMAL(10,2) , 
		  "FIX_CHG" DECIMAL(10,2) , 
		  "APPLICANT_SIGN" BLOB(1048576) LOGGED NOT COMPACT , 
		  "RAPIDLOC" VARCHAR(300 OCTETS) , 
		  "RAPIDFAULT" VARCHAR(100 OCTETS) , 
		  "ITEM_CATEGORY" VARCHAR(20 OCTETS) , 
		  "ITEM_NAME" VARCHAR(20 OCTETS) , 
		  "ADJSTMENT_STATUS" VARCHAR(10 OCTETS) , 
		  "CSC_TRACKING_HISTORY" VARCHAR(4000 OCTETS) , 
		  "ESCALLATION_JSON" VARCHAR(4000 OCTETS) , 
		  "ACKNOWLEDGEMENT_ID" VARCHAR(25 OCTETS) )   
		 IN "TS_CFG_16"  
		 ORGANIZE BY ROW  ;

CREATE INDEX "DB2INST1"."IDX1" ON "DB2INST1"."CSTREQUEST_T_BACKUP" 
		("ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

GRANT SELECT ON TABLE "DB2INST1"."CSTREQUEST_T_BACKUP" TO ROLE "ROLE_READ_ONLY"  ;

GRANT CONTROL ON TABLE "DB2INST1"."CSTREQUEST_T_BACKUP" TO USER "DB2INST1"  ;


-- DB2INST1.DATABASE_QUERY_LOG_BACK definition

CREATE TABLE "DB2INST1"."DATABASE_QUERY_LOG_BACK"  (
		  "ID" VARCHAR(20 OCTETS) , 
		  "CREATED_BY" VARCHAR(15 OCTETS) , 
		  "CREATE_DATE" TIMESTAMP , 
		  "STMT_TYPE" VARCHAR(10 OCTETS) , 
		  "SQL_TEXT" VARCHAR(2200 OCTETS) , 
		  "ROWS_EFFECTED" DECFLOAT(16) , 
		  "REMARKS" VARCHAR(100 OCTETS) , 
		  "DB_IP_ADDRESS" VARCHAR(20 OCTETS) , 
		  "SOURCE_OFFICE_ID" VARCHAR(15 OCTETS) , 
		  "TARGET_OFFICE_ID" VARCHAR(15 OCTETS) , 
		  "RECORD_STATUS" VARCHAR(10 OCTETS) , 
		  "UPDATED_BY" VARCHAR(15 OCTETS) , 
		  "UPDATE_DATE" TIMESTAMP , 
		  "SCREEN_ID" VARCHAR(30 OCTETS) , 
		  "MONTH" DECIMAL(2,0) , 
		  "YEAR" DECIMAL(4,0) , 
		  "FLAG1" VARCHAR(20 OCTETS) , 
		  "FLAG2" VARCHAR(20 OCTETS) , 
		  "FLAG3" VARCHAR(1 OCTETS) , 
		  "FLAG4" VARCHAR(1 OCTETS) , 
		  "FLAG5" VARCHAR(1 OCTETS) , 
		  "MODULE_ID" VARCHAR(15 OCTETS) , 
		  "SUBMODULE_ID" VARCHAR(15 OCTETS) )   
		 IN "TS8"  
		 ORGANIZE BY ROW  ;

GRANT SELECT ON TABLE "DB2INST1"."DATABASE_QUERY_LOG_BACK" TO ROLE "ROLE_READ_ONLY"  ;

GRANT CONTROL ON TABLE "DB2INST1"."DATABASE_QUERY_LOG_BACK" TO USER "DB2INST1"  ;


-- DB2INST1.EAS_DATE definition

CREATE TABLE "DB2INST1"."EAS_DATE"  (
		  "ACCOUNT_NO" VARCHAR(20 OCTETS) , 
		  "NAME" VARCHAR(300 OCTETS) , 
		  "JUNCTION_NAME" VARCHAR(70 OCTETS) , 
		  "DTR_NAME" VARCHAR(100 OCTETS) , 
		  "METER_BOX_NUMBER" VARCHAR(100 OCTETS) , 
		  "C1_1393_METER_READING_DATE" TIMESTAMP , 
		  "C1_1393_CAT" VARCHAR(50 OCTETS) , 
		  "C1_1393_MF" DECIMAL(10,4) , 
		  "C1_1393_BILL_UNITS" DECIMAL(8,0) , 
		  "C1_1393_ENERGY_CHG" DECIMAL(15,5) , 
		  "C1_1393_TOTAL_CHG" DECIMAL(15,5) , 
		  "C1_1393_BILL_CHG" DECIMAL(15,5) , 
		  "C1_1393_AMOUNT_PAID" DECIMAL(10,2) , 
		  "C2_1393_METER_READING_DATE" TIMESTAMP , 
		  "C2_1393_CAT" VARCHAR(50 OCTETS) , 
		  "C2_1393_MF" DECIMAL(10,4) , 
		  "C2_1393_BILL_UNITS" DECIMAL(8,0) , 
		  "C2_1393_ENERGY_CHG" DECIMAL(15,5) , 
		  "C2_1393_TOTAL_CHG" DECIMAL(15,5) , 
		  "C2_1393_BILL_CHG" DECIMAL(15,5) , 
		  "C2_1393_AMOUNT_PAID" DECIMAL(10,2) , 
		  "C3_1393_METER_READING_DATE" TIMESTAMP , 
		  "C3_1393_CAT" VARCHAR(50 OCTETS) , 
		  "C3_1393_MF" DECIMAL(10,4) , 
		  "C3_1393_BILL_UNITS" DECIMAL(8,0) , 
		  "C3_1393_ENERGY_CHG" DECIMAL(15,5) , 
		  "C3_1393_TOTAL_CHG" DECIMAL(15,5) , 
		  "C3_1393_BILL_CHG" DECIMAL(15,5) , 
		  "C3_1393_AMOUNT_PAID" DECIMAL(10,2) , 
		  "C4_1393_METER_READING_DATE" TIMESTAMP , 
		  "C4_1393_CAT" VARCHAR(50 OCTETS) , 
		  "C4_1393_MF" DECIMAL(10,4) , 
		  "C4_1393_BILL_UNITS" DECIMAL(8,0) , 
		  "C4_1393_ENERGY_CHG" DECIMAL(15,5) , 
		  "C4_1393_TOTAL_CHG" DECIMAL(15,5) , 
		  "C4_1393_BILL_CHG" DECIMAL(15,5) , 
		  "C4_1393_AMOUNT_PAID" DECIMAL(10,2) , 
		  "C5_1393_METER_READING_DATE" TIMESTAMP , 
		  "C5_1393_CAT" VARCHAR(50 OCTETS) , 
		  "C5_1393_MF" DECIMAL(10,4) , 
		  "C5_1393_BILL_UNITS" DECIMAL(8,0) , 
		  "C5_1393_ENERGY_CHG" DECIMAL(15,5) , 
		  "C5_1393_TOTAL_CHG" DECIMAL(15,5) , 
		  "C5_1393_BILL_CHG" DECIMAL(15,5) , 
		  "C5_1393_AMOUNT_PAID" DECIMAL(10,2) , 
		  "C6_1393_METER_READING_DATE" TIMESTAMP , 
		  "C6_1393_CAT" VARCHAR(50 OCTETS) , 
		  "C6_1393_MF" DECIMAL(10,4) , 
		  "C6_1393_BILL_UNITS" DECIMAL(8,0) , 
		  "C6_1393_ENERGY_CHG" DECIMAL(15,5) , 
		  "C6_1393_TOTAL_CHG" DECIMAL(15,5) , 
		  "C6_1393_BILL_CHG" DECIMAL(15,5) , 
		  "C6_1393_AMOUNT_PAID" DECIMAL(10,2) , 
		  "C1_1394_METER_READING_DATE" TIMESTAMP , 
		  "C1_1394_CAT" VARCHAR(50 OCTETS) , 
		  "C1_1394_MF" DECIMAL(10,4) , 
		  "C1_1394_BILL_UNITS" DECIMAL(8,0) , 
		  "C1_1394_ENERGY_CHG" DECIMAL(15,5) , 
		  "C1_1394_TOTAL_CHG" DECIMAL(15,5) , 
		  "C1_1394_BILL_CHG" DECIMAL(15,5) , 
		  "C1_1394_AMOUNT_PAID" DECIMAL(10,2) )   
		 IN "TS8"  
		 ORGANIZE BY ROW  ;

GRANT SELECT ON TABLE "DB2INST1"."EAS_DATE" TO ROLE "ROLE_READ_ONLY"  ;

GRANT CONTROL ON TABLE "DB2INST1"."EAS_DATE" TO USER "DB2INST1"  ;


-- DB2INST1.MTR_139394 definition

CREATE TABLE "DB2INST1"."MTR_139394"  (
		  "CONS_NUMBER" VARCHAR(20 OCTETS) , 
		  "OFFICE_ID" VARCHAR(20 OCTETS) )   
		 IN "TS8"  
		 ORGANIZE BY ROW  ;

CREATE INDEX "DABS    "."CONS_NUMBER_MTR" ON "DB2INST1"."MTR_139394" 
		("CONS_NUMBER" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

CREATE INDEX "DABS    "."OFFICE_MTR" ON "DB2INST1"."MTR_139394" 
		("OFFICE_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

GRANT SELECT ON TABLE "DB2INST1"."MTR_139394" TO ROLE "ROLE_READ_ONLY"  ;

GRANT CONTROL ON TABLE "DB2INST1"."MTR_139394" TO USER "DB2INST1"  ;


-- DB2INST1.NAME_CONV definition

CREATE TABLE "DB2INST1"."NAME_CONV"  (
		  "OFFICE_ID" VARCHAR(20 OCTETS) , 
		  "NAME" VARCHAR(300 OCTETS) NOT NULL , 
		  "FATHER_NAME" VARCHAR(100 OCTETS) , 
		  "ADDRESS_1" VARCHAR(500 OCTETS) , 
		  "ACCOUNT_NO" VARCHAR(20 OCTETS) NOT NULL , 
		  "ESTERAK_NO" VARCHAR(25 OCTETS) NOT NULL )   
		 IN "TS8"  
		 ORGANIZE BY ROW  ;

GRANT SELECT ON TABLE "DB2INST1"."NAME_CONV" TO ROLE "ROLE_READ_ONLY"  ;

GRANT CONTROL ON TABLE "DB2INST1"."NAME_CONV" TO USER "DB2INST1"  ;


-- DB2INST1.NOTTOBILL_EXCEPTIONS definition

CREATE TABLE "DB2INST1"."NOTTOBILL_EXCEPTIONS"  (
		  "ACCOUNT_NO" VARCHAR(50 OCTETS) , 
		  "JUNCTION" VARCHAR(50 OCTETS) , 
		  "PRST_MTR_ID" VARCHAR(50 OCTETS) , 
		  "BILL_DET_ID" VARCHAR(50 OCTETS) , 
		  "PREV_CYCLE" VARCHAR(50 OCTETS) , 
		  "PREV_YEAR" VARCHAR(50 OCTETS) , 
		  "PREV_PREV_RDG_KWH" DECIMAL(30,4) , 
		  "PREV_PRST_RDG_KWH" DECIMAL(30,4) , 
		  "PREV_PRES_TOD_CURRENT" DECIMAL(30,4) , 
		  "PREV_PREV_STATUS_KWH" VARCHAR(100 OCTETS) , 
		  "PRST_PREV_STATUS_KWH" VARCHAR(100 OCTETS) , 
		  "PRST_PRST_STATUS_KWH" VARCHAR(100 OCTETS) , 
		  "PREV_PREV_RDG_DATE" TIMESTAMP , 
		  "PREV_PRST_RDG_DATE" TIMESTAMP , 
		  "PRST_PREV_RDG_DATE" TIMESTAMP , 
		  "PRST_PRST_RDG_DATE" TIMESTAMP , 
		  "PRST_PREV_RDG_KWH" DECIMAL(30,4) , 
		  "PRST_PRST_RDG_KWH" DECIMAL(30,4) , 
		  "PRST_MF_KWH" VARCHAR(50 OCTETS) , 
		  "PRST_CYCLE" VARCHAR(50 OCTETS) , 
		  "PRST_YEAR" VARCHAR(50 OCTETS) , 
		  "PRST_BILL_REC_KWH" DECIMAL(30,4) , 
		  "PRST_COMPUTED_KWH" DECIMAL(30,4) , 
		  "CREATE_DATE" TIMESTAMP , 
		  "EXCP_CASE" VARCHAR(200 OCTETS) , 
		  "RECORD_STATUS" VARCHAR(200 OCTETS) , 
		  "MTR_ID" VARCHAR(200 OCTETS) , 
		  "UPDATED_BY" VARCHAR(50 OCTETS) )   
		 IN "TS8"  
		 ORGANIZE BY ROW  ;

CREATE INDEX "DB2INST1"."IDX1_NOTTOBILL_EXCP" ON "DB2INST1"."NOTTOBILL_EXCEPTIONS" 
		("ACCOUNT_NO" ASC,
		 "EXCP_CASE" ASC,
		 "RECORD_STATUS" ASC,
		 "PRST_CYCLE" ASC,
		 "PRST_YEAR" ASC)
		
		COLLECT SAMPLED DETAILED STATISTICS 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS ;

GRANT SELECT ON TABLE "DB2INST1"."NOTTOBILL_EXCEPTIONS" TO ROLE "ROLE_READ_ONLY"  ;

GRANT SELECT ON TABLE "DB2INST1"."NOTTOBILL_EXCEPTIONS" TO USER "ETLUSER "  ;

GRANT SELECT ON TABLE "DB2INST1"."NOTTOBILL_EXCEPTIONS" TO USER "ZAFAR   "  ;

GRANT CONTROL ON TABLE "DB2INST1"."NOTTOBILL_EXCEPTIONS" TO USER "DB2INST1"  ;


-- DB2INST1.SHKASSIGNMENTSTABLE_190915 definition

CREATE TABLE "DB2INST1"."SHKASSIGNMENTSTABLE_190915"  (
		  "ACTIVITY" DECIMAL(19,0) NOT NULL , 
		  "THERESOURCE" DECIMAL(19,0) NOT NULL , 
		  "ACTIVITYID" VARCHAR(100 OCTETS) NOT NULL , 
		  "ACTIVITYPROCESSID" VARCHAR(100 OCTETS) NOT NULL , 
		  "ACTIVITYPROCESSDEFNAME" VARCHAR(200 OCTETS) NOT NULL , 
		  "RESOURCEID" VARCHAR(100 OCTETS) NOT NULL , 
		  "ISACCEPTED" SMALLINT NOT NULL , 
		  "ISVALID" SMALLINT NOT NULL , 
		  "CNT" DECIMAL(19,0) NOT NULL , 
		  "OID" DECIMAL(19,0) NOT NULL , 
		  "VERSION" INTEGER NOT NULL )   
		 IN "TS8"  
		 ORGANIZE BY ROW  ;

GRANT SELECT ON TABLE "DB2INST1"."SHKASSIGNMENTSTABLE_190915" TO ROLE "ROLE_READ_ONLY"  ;

GRANT CONTROL ON TABLE "DB2INST1"."SHKASSIGNMENTSTABLE_190915" TO USER "DB2INST1"  ;


-- DB2INST1.ZONE_OFFICE_CATEGORY_RELATION definition

CREATE TABLE "DB2INST1"."ZONE_OFFICE_CATEGORY_RELATION"  (
		  "ID" VARCHAR(30 OCTETS) , 
		  "KED" VARCHAR(20 OCTETS) , 
		  "ZONE" VARCHAR(30 OCTETS) , 
		  "ZONE_ID" VARCHAR(10 OCTETS) , 
		  "JUNCTION" VARCHAR(30 OCTETS) , 
		  "JUNCTION_ID" VARCHAR(50 OCTETS) , 
		  "CATEGORY" VARCHAR(50 OCTETS) , 
		  "CATEGORY_ID" VARCHAR(30 OCTETS) , 
		  "PARENT_OFFICEID" VARCHAR(30 OCTETS) , 
		  "RECORD_STATUS" VARCHAR(20 OCTETS) , 
		  "CHECK_CONDITION" VARCHAR(100 OCTETS) , 
		  "CREATE_DATE" TIMESTAMP , 
		  "UPDATE_DATE" TIMESTAMP , 
		  "NAME" VARCHAR(30 OCTETS) , 
		  "COMM_ID" VARCHAR(30 OCTETS) , 
		  "PARENT" VARCHAR(30 OCTETS) , 
		  "PRIORITY" VARCHAR(10 OCTETS) )   
		 IN "TS8"  
		 ORGANIZE BY ROW  ;

GRANT SELECT ON TABLE "DB2INST1"."ZONE_OFFICE_CATEGORY_RELATION" TO ROLE "ROLE_READ_ONLY"  ;

GRANT CONTROL ON TABLE "DB2INST1"."ZONE_OFFICE_CATEGORY_RELATION" TO USER "DB2INST1"  ;